### ISSUE TITLE
eMail ends up in spam when sent to google

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#104]
Hi, I am wondering if you can help find out why legit email sent from our servers is considered spam by google.

Just had an email sent to my email address (which is in haraka server) from one of our cpanel servers. Without showing all the headers would the following Karma scoring be enough to tell?

X-Haraka-Karma: score: 2, good: 2, bad: 28, connections: 61, history: -26, awards: 004,005,086,100,131,182,256

The mail with the above Karma score did not end up in my spam by the way. But the very same email when sent to a client from the same cpanel server ends up in spam.
Thanks.

**Comment by msimerson** [comment]
There's a problem with your SPF record (sorry, I haven't had time to explain), which is why Gmail is filtering it to spam.

**Comment by toastedmail** [comment]
Hi,
Can you please tell me from the mail headers below what is wrong with spf? 

SPF Record: 
barontel.com.           14400   IN      TXT     "v=spf1 +a +mx +ip4:104.193.49.17/32 +ip4:104.193.49.202/32 +a:smtpd.barontel.net -all"

From donotreply@barontel.com Thu Nov 10 21:38:24 2016
Return-Path: <donotreply@barontel.com>
Delivered-To: servaris.com-lbaron@servaris.com
Received: (qmail 92345 invoked by uid 89); 10 Nov 2016 21:38:24 -0000
Received: from unknown (HELO mxbt1.barontel.com) (172.16.15.9)
  by vpopmail with SMTP; 10 Nov 2016 21:38:24 -0000
Authentication-Results: mxbt1.barontel.com; spf=pass smtp.mailfrom=barontel.com
Received-SPF: Pass (mxbt1.barontel.com: domain of barontel.com designates 104.193.49.202 as permitted sender) receiver=mxbt1.barontel.com; identity=mailfrom; client-ip=104.193.49.202; helo=barontel.com; envelope-from=<donotreply@barontel.com>
Received-SPF: Pass (mxbt1.barontel.com: domain of barontel.com designates 104.193.49.202 as permitted sender) receiver=mxbt1.barontel.com; identity=helo; client-ip=104.193.49.202; helo=barontel.com; envelope-from=<donotreply@barontel.com>
Received: from barontel.com ([104.193.49.202])
	by mxbt1.barontel.com (Haraka/2.8.10) with ESMTPS id ED07FA60-2DB1-458C-8985-15C399FF227F.1
	envelope-from <donotreply@barontel.com>
	(version=TLSv1/SSLv3 cipher=ECDHE-RSA-AES256-GCM-SHA384 verify=FAIL);
	Thu, 10 Nov 2016 16:38:22 -0500
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed;
	d=barontel.com; s=default; h=Content-Transfer-Encoding:Content-Type:
	MIME-Version:Message-ID:Subject:From:To:Date:Sender:Reply-To:Cc:Content-ID:
	Content-Description:Resent-Date:Resent-From:Resent-Sender:Resent-To:Resent-Cc
	:Resent-Message-ID:In-Reply-To:References:List-Id:List-Help:List-Unsubscribe:
	List-Subscribe:List-Post:List-Owner:List-Archive;
	bh=jetFasjWbdcMqurbri6sF9HEy/rusyEdS46gZ7NBiUo=; b=GlfRYefIICcCeXyriqKiuSn1x1
	G0BzDAFUlFylVrNwPGCSQ5nGkM1k989S874b/HVa1W6aA3y2EATfY3tsFgFZnvGHDIu0l12WuYG5K
	YfhV4sG5aoQzqQT+7syPVY1szQ/fEi3jNrpumzprdIEKfPKxBw0YyenA0fs8/rhR17JM1a6sIlNYF
	XBMMzP3bRiyyM0s5WQScRo1BwAJBP0tDRfhT2Gwt4nQE14pyo+fgTJ/XRqnBtvCMTOvhYmlNtzdbF
	/npSirkxFfhOvhZbimLqahna+P0Bwm1mRHpXdP4LB3vUoc90sjg6ALfZbmt/azcDVc8G0QT1T1hAF
	LaYC7Gvw==;
Received: from [104.193.49.202] (port=44002 helo=my.barontel.com)
	by cpan.tier1hosting.net with esmtpsa (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.87)
	(envelope-from <donotreply@barontel.com>)
	id 1c4x34-0003rD-8A; Thu, 10 Nov 2016 16:38:18 -0500
