### ISSUE TITLE
How-to for HaProxy and multiple domain SSL certificates

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#109]
In a MT6 environment one can have multiple domains and haproxy will provide the right SSL certificate for each of your domain names.

You'll need your ca-bundle or intermediate certificate(s) and your private key and of course your crt from the place you purchased the signed certificate from.

You'll want to mount your haproxy jail because you're going to need to restart haproxy

`#jailmanage haproxy`
`#cat server.key intermediate.crt signed_crt.crt > mydomain.pem`
place mydomain.pem in /etc/ssl/private/

`#cat server.key.crt ca-bundle.crt other-signed_crt.crt > myotherdomain.pem`
place myotherdomain.pem in /etc/ssl/private

create a file for haproxy to find the certs:
#vim /etc/ssl/private/crt-list.txt and insert the lines as they are below changing the name to your .pem file names.
/etc/ssl/private/mydomain.pem
/etc/ssl/private/myotherdomain.pem

save the file `:wq`

`#vim /usr/local/etc/haproxy.conf`
comment out '#' the line in the heading `frontend https-in`:
 bind *:443 ssl crt /etc/ssl/private
and insert:
`bind *:443 ssl crt-list /etc/ssl/private/crt-list.txt`

Save the file: :wq

`#/usr/local/etc/rc.d/haproxy restart`
Your done.
#exit

.

**Comment by msimerson** [comment]
Thanks @toastedmail 

Please copy/paste this content into a Wiki page and then link to it from the [Haproxy](https://github.com/msimerson/Mail-Toaster-6/wiki/Haproxy) details page.

**Comment by toastedmail** [comment]
What edit mode do you write in? Trying to get any commands to be 'code' but none of the modes let it happen.

**Comment by msimerson** [comment]
[GFM](https://help.github.com/categories/writing-on-github/)

**Comment by toastedmail** [comment]
GFM??? What is that?

**Comment by toastedmail** [comment]
All of a sudden, can't send to smtp server: 

haraka haraka[3718]: [INFO] [C46E1C0F-25D9-4B7F-98AC-10EF5A64190D] [limit] unrec_cmds: 1, pass:1/10, fail:unrecognized: AUTH,CRAM-MD5, unrecognized: AUTH,CRAM-MD5

/data/haraka/config/plugins
auth/flat_file

The rest are #'d out.

**Comment by msimerson** [comment]
> GFM??? What is that?

It's a link to docs for GitHub Flavored Markdown. Click it.

**Comment by toastedmail** [comment]
Click what / where??

**Comment by msimerson** [comment]
The original GFM that's written in blue letters. They're these thinks called "links" and they're normally hilited in blue and when you click them, they take you places.

**Comment by toastedmail** [comment]
Sounds like you are talking about <a href="blah.com/interesting_page.php">Interesting</a>

**Comment by toastedmail** [comment]
In auth_flat_file.ini have:
[core]
methods=PLAIN,LOGIN,CRAM-MD5

Why then the error: unrecognized: AUTH,CRAM-MD5, unrecognized: AUTH,CRAM-MD5

**Comment by toastedmail** [comment]
openssl s_connect ..... :465

250 STARTTLS
ehlo hi.there
250-smtpd.domain.net Hello CPE4c5e0c417c51-CMbc4dfb28e2d0.cpe.net
[99.237.72.210], Haraka is at your service.
250-PIPELINING
250-8BITMIME
250-SIZE 52428800
250-AUTH PLAIN LOGIN CRAM-MD5
`250 AUTH PLAIN LOGIN`

Is the 2nd 250 a hint cram-md5 is not working?
