### ISSUE TITLE
Spam with dangerous content getting in

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#112]
Firstly, I say 'dangerous' because someone could easily click on the link in the email. For instance here is one that just arrived:

**purchasing at servaris NEVER wrote this person either.**

> I am sorry but we will not pay this. You are trying to rip us.
> 
> On Thu, Nov 16, 2016 at 2:14 PM,  purchasing@servaris.com wrote:
> 
> Here is the bill... I am waiting for your payment
> 
> BILL #78813437 
> The link for the above BILL is: http://zombiewar.**vn**/teaser/view.php?id=cHVyY2hhc2luZ0BzZXJ2YXJpcy5jb20=
> 

The headers show failed SPF:
Received-SPF: None (mxbt1.barontel.com: domain of kardol.com does not designate 50.78.36.4 as permitted sender) receiver=mxbt1.barontel.com; identity=mailfrom; client-ip=50.78.36.4; helo=kardol.com; envelope-from=<mike@kardol.com>
Received-SPF: None (mxbt1.barontel.com: domain of kardol.com does not designate 50.78.36.4 as permitted sender) receiver=mxbt1.barontel.com; identity=helo; client-ip=50.78.36.4; helo=kardol.com; envelope-from=<mike@kardol.com>
Received: from kardol.com (50-78-36-4-static.hfc.comcastbusiness.net [50.78.36.4])

Here is another spam arriving earlier today:

Dear Domain Owner,

Our system has detected that your domain: Peer1.host is being used for spamming and spreading malware recently.
You can download the detailed abuse report of your domain along with date/time of incidents. Click Here

We have also provided detailed instruction on how to delist your domain from our blacklisting.

Please download the report immediately and take proper action within 24 hours otherwise your domain will be suspended permanently.

There is also possibility of legal action depend on severity and persistence of your abuse case.

Three Simple Steps:
1. Download your abuse report.
2. Check your domain abuse incidents along with date and time.
3. Take few simple steps for prevention and to avoid domain suspension.

**Click Here to Download your Report (link for this is http://www.domaincop.net/e.386Fz4Rpdw23DjWlMtKmuhsFVuOlytimVuhszhOV2f0/Corsican-cryptographic )**

Please look into it and contact us.

Best Regards,
Domain Abuse Admin
DomainCop Inc.
Tel.: (139) 719-51-12 

The phone number above doesn't exist in North America.

**Comment by msimerson** [comment]
You have plenty of tools already installed that can solve this.

**Comment by toastedmail** [comment]
What tools are you referring to exactly.
