### ISSUE TITLE
Enhancing spam protection

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#114]
Would the main protection for spam be karma.ini?

**Comment by msimerson** [comment]
You have karma, spamassassin, rspamd, clamav, clamav unofficial, DNSBLs, and a handful of Haraka plugins that all contribute to reliable and effective filtering. Few spam tools are plug-n-play. Spammers are human and continually evolve in their methods to evade filtering. Which means, filters need to learn and adapt to be effective. Expect to **work** at it to get excellent filtering.

**Comment by toastedmail** [comment]
Yes, but one has to be knowledgeable in those programs you've mentioned. I've gone an contributed a bit of a how-to for HaProxy. Why you don't put up page on how-to for karma (the karma.ini is too terse) and perhaps spamasassin is beyond me. You know it like the back of your hand.
