### ISSUE TITLE
Positive/Negative for karma.ini

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#115]
Please explain a little better on what both positive and negative values do.
example:
181 = data.headers | fail       | match  |   from_match | -1 | Envelope From does not match Message From:
182 = data.headers | pass       | match  |   from_match |  1 | Envelope From matches Message From:
183 = data.headers | fail       | equals |           UA | -1 | Uncommon MUA
184 = data.headers | fail       | match  | direct-to-mx | -1 | Not relayed
185 = data.headers | fail       | match  |      missing | -1 | Missing a required header

-1 = a bad hit ? The sender gets a -1 added to their karma score and if the total score goes to either -8 or -9 mail is reject with very bad karma? If yes, do the positive and negative apply to everything in karma.ini?

**Comment by msimerson** [comment]
> Please explain a little better

RTFM on [the web](https://github.com/haraka/Haraka/blob/master/docs/plugins/karma.md) or with `haraka -h karma`.

> If yes, do the positive and negative apply to everything in karma.ini?

Everything that matches the rules, yes.
