### ISSUE TITLE
provision vpopmail stops at fetch: /qmail/filter.txt: No such file or directory

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#123]
Was in process of updating vpopmail
`#  sudo sh`  
`#  . mail-toaster.sh`  
`#  provision host`  
`#  provision base`  
`#  provision vpopmail`  
172.16.15.8
provision-vpopmail.sh                         100% of 7032  B   18 MBps 00m00s
loading config from mail-toaster.conf
mysql enabled
toaster host: mxbt1.barontel.com
email domain: barontel.com
shell: /bin/csh
safe name: stage
zroot/jails/base-10.2-RELEASE@p25 snapshot exists

   ***   stage cleanup   ***

service jail stop stage
Stopping jails:.
jail -r stage
zroot/data/vpopmail filesystem exists

   ***   stage jail filesystem setup   ***

zfs clone zroot/jails/base-10.2-RELEASE@p25 zroot/jails/stage
sysrc -R /jails/stage hostname=vpopmail
hostname: base -> vpopmail

   ***   creating data volume   ***

zroot/data/vpopmail filesystem exists
zroot/data/vpopmail filesystem exists
mkdir -p /jails/stage/usr/local/vpopmail
mount_nullfs /data/vpopmail /jails/stage/usr/local/vpopmail
mount /jails/stage/usr/ports
mount /jails/stage/var/cache/pkg

   ***   stage jail stage startup   ***

Setting hostname: vpopmail.
Starting syslogd.
ELF ldconfig path: /lib /usr/lib /usr/lib/compat /usr/local/lib
32-bit compatibility ldconfig path: /usr/lib32
Clearing /tmp (X related).
Starting cron.

Fri Nov 25 00:51:37 EST 2016
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.

   ***   setting up data fs for qmail control files   ***

jexec stage ln -s /usr/local/vpopmail/qmail-control /var/qmail/control
jexec stage ln -s /usr/local/vpopmail/qmail-users /var/qmail/users

   ***   installing qmail   ***

pkg -j stage install -y netqmail daemontools ucspi-tcp
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
The following 3 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        netqmail: 1.06_3
        daemontools: 0.76_18
        ucspi-tcp: 0.88_2

Number of packages to be installed: 3

The process will require 2 MiB more space.
341 KiB to be downloaded.
[vpopmail] Fetching netqmail-1.06_3.txz: 100%  226 KiB 231.4kB/s    00:01
[vpopmail] Fetching daemontools-0.76_18.txz: 100%   51 KiB  52.7kB/s    00:01
[vpopmail] Fetching ucspi-tcp-0.88_2.txz: 100%   64 KiB  65.1kB/s    00:01
Checking integrity... done (0 conflicting)
[vpopmail] [1/3] Installing netqmail-1.06_3...
===> Creating groups.
Creating group 'qmail' with gid '82'.
Creating group 'qnofiles' with gid '81'.
===> Creating users
Creating user 'alias' with uid '81'.
Creating user 'qmaild' with uid '82'.
Creating user 'qmaill' with uid '83'.
Creating user 'qmailp' with uid '84'.
Creating user 'qmailq' with uid '85'.
Creating user 'qmailr' with uid '86'.
Creating user 'qmails' with uid '87'.
[vpopmail] [1/3] Extracting netqmail-1.06_3: 100%

A /usr/local/etc/rc.d/qmailsmtpd and a /usr/local/etc/rc.d/qmailsend
symlink were created.

[vpopmail] [2/3] Installing daemontools-0.76_18...
[vpopmail] [2/3] Extracting daemontools-0.76_18: 100%
[vpopmail] [3/3] Installing ucspi-tcp-0.88_2...
[vpopmail] [3/3] Extracting ucspi-tcp-0.88_2: 100%
Message from netqmail-1.06_3:
ATTENTION:

You can enable qmail as your default mailer executing:
> /var/qmail/scripts/enable-qmail
Message from ucspi-tcp-0.88_2:
===>   NOTICE:

The ucspi-tcp port currently does not have a maintainer. As a result, it is
more likely to have unresolved issues, not be up-to-date, or even be removed in
the future. To volunteer to maintain this port, please create an issue at:

https://bugs.freebsd.org/bugzilla

More information about port maintainership is available at:

https://www.freebsd.org/doc/en/articles/contributing/ports-contributing.html#maintain-port
mail_qmail_SET=DNS_CNAME DOCS MAILDIRQUOTA_PATCH
mail_qmail_UNSET=RCDLINK

   ***   enabling qmail   ***

jexec stage /var/qmail/scripts/enable-qmail
===> I hope you know what you are doing:
===> You just told your system to not
===> automaticaly start sendmail on your
===> next startup.
===> (i.e., added sendmail_enable="NONE" to rc.conf)
===> Do not forget to choose an appropriate qmail startup
===> script. Go through /var/qmail/boot, choose one
===> and copy the chosen script as /var/qmail/rc
===> For example, "cp /var/qmail/boot/proc+df /var/qmail/rc"
postmaster@barontel.com
postmaster@barontel.com
postmaster@barontel.com

   ***   installing maildrop   ***

pkg -j stage install -y maildrop
Updating FreeBSD repository catalogue...
FreeBSD repository is up-to-date.
All repositories are up-to-date.
The following 3 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        maildrop: 2.8.4
        courier-unicode: 1.4
        pcre: 8.39

Number of packages to be installed: 3

The process will require 7 MiB more space.
2 MiB to be downloaded.
[vpopmail] Fetching maildrop-2.8.4.txz: 100%  328 KiB 336.3kB/s    00:01
[vpopmail] Fetching courier-unicode-1.4.txz: 100%  101 KiB 103.7kB/s    00:01
[vpopmail] Fetching pcre-8.39.txz: 100%    1 MiB 581.6kB/s    00:02
Checking integrity... done (0 conflicting)
[vpopmail] [1/3] Installing courier-unicode-1.4...
[vpopmail] [1/3] Extracting courier-unicode-1.4: 100%
[vpopmail] [2/3] Installing pcre-8.39...
[vpopmail] [2/3] Extracting pcre-8.39: 100%
[vpopmail] [3/3] Installing maildrop-2.8.4...
[vpopmail] [3/3] Extracting maildrop-2.8.4: 100%

   ***   installing maildrop filter file   ***

fetch: /qmail/filter.txt: No such file or directory
#

**Comment by msimerson** [comment]
Your mail-toaster.sh file is out of date. I added an update step in the [Updating](https://github.com/msimerson/Mail-Toaster-6/wiki/Updating) instructions.
