### ISSUE TITLE
provision vpopmail stops at 

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#127]
After seeing your message about updating mail-toaster.sh

`# sudo sh`
`# fetch .... mail-toaster.sh`
`# . mail-toaster.sh`
`# service jail stop`
`#  provision host`
`# provision base`
`# service jail start`

`# provision vpopmail`
.
.
[MSG] Installing of Qmail::Deliverable successful
ln -s /var/service /service
supervising qmail-smtpd
supervising qmail-send
supervising vpopmaild
supervising qmail-deliverabled
svscan_enable:  -> YES
svscan not running?
Starting svscan.
testing vpopmail
checking for port 25 listener in staged jail
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS
89       tcpserver  54951 3  tcp4   172.16.15.254:25      *:*
checking for port 80 listener in staged jail
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS
www      lighttpd   54114 4  tcp4   172.16.15.254:80      *:*
checking for port 89 listener in staged jail
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS
root     tcpserver  54953 3  tcp4   172.16.15.254:89      *:*
checking for port 8998 listener in staged jail
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS
root     perl       54955 4  tcp4   172.16.15.254:8998    *:*
checking for process lighttpd in staged jail
pgrep: Invalid jail ID `stage'  
  **#**

**Comment by toastedmail** [comment]
Tried again just because you wrote it's not necessary to run` provision host`  
Same as above, near `testing vpopmail ` it stops immediately after` pgrep: Invalid jail ID `stage'`

**Comment by toastedmail** [comment]
Also noticed the following;
`# jls`
15  172.16.15.254   vpopmail                      /jails/stage

**Comment by msimerson** [comment]
Dunno. It works for me:

````
checking for port 8998 listener in staged jail
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS      
root     perl       75071 4  tcp4   172.16.15.254:8998    *:*
checking for process lighttpd in staged jail
74321
it worked

   ***   promoting jail vpopmail   ***

service jail stop stage
...
````

**Comment by toastedmail** [comment]
Tried to fix this;
umount -f /jails/stage

The above didn't help.
Took out vpopmail in /etc/rc.conf
rebooted
jls did not show any vpopmail or stage.

Put back vpopmail in /etc/rc.conf jail_list
rebooted

Same ... it stops 

`pgrep: Invalid jail ID `stage'  `
#    
`# jls  `
   JID  IP Address      Hostname                      Path
     1  172.16.15.3     dns                           /jails/dns
     2  172.16.15.4     mysql                         /jails/mysql
     3  172.16.15.8     vpopmail                      /jails/vpopmail
     4  172.16.15.15    dovecot                       /jails/dovecot
     5  172.16.15.10    webmail                       /jails/webmail
     6  172.16.15.12    haproxy                       /jails/haproxy
     7  172.16.15.5     clamav                        /jails/clamav
     8  172.16.15.14    avg                           /jails/avg
     9  172.16.15.16    redis                         /jails/redis
    10  172.16.15.13    rspamd                        /jails/rspamd
    11  172.16.15.17    geoip                         /jails/geoip
    12  172.16.15.6     spamassassin                  /jails/spamassassin
    13  172.16.15.9     haraka                        /jails/haraka
    14  172.16.15.254   vpopmail                      /jails/stage

` #  `

**Comment by msimerson** [comment]
Are you using a version of FreeBSD older than 10.3?

**Comment by toastedmail** [comment]
No, the box was originally 10.2. Upgraded it to 10.3 a week or so ago.

I have changed a new mt6 to replace the one that wont build vpopmail. This box was built using 10.3 iso.

Have place my sni cert in /etc/ssl/private and /etc/ssl/erts as well as in haproxy. 

Watching maillog it complaining about ssl key

Nov 26 20:41:41 dovecot dovecot: master: Error: service(imap-login): command startup failed, throttling for 2 secs
Nov 26 20:41:41 dovecot dovecot: imap-login: Fatal: Can't load private ssl_key: Key is for a different cert than ssl_cert

I take it there is cert and key issue in /data/dovecot/etc/ssl

What must I do to fix this since its /data and provision dovecot won't fix this?

**Comment by toastedmail** [comment]
See now the certs in /data/dovecot/etc/ssl/  are for mxbt3, the original name of this mt6. Its now mxbt1 

I fixed by

**Comment by toastedmail** [comment]
I screwed up.

Regards,
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
Lanny Baron
BaronTEL

The Future of Business Telephony Services is Here and Now!

Tel: 416.477.5411
Toll-Free: 888.241.8647
Fax: 647.693.9492
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
