### ISSUE TITLE
Haraka config dir much less content

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#129]
On newly installed MT6, notice there are a lot of files not in /data/haraka/config
would you recommend rsync'ing old-server:/data/haraka/config/ /data/haraka/config ?

**Comment by msimerson** [comment]
Newer haraka's include everything in the default install dirs config and now only overrides go in your installed/config dir. Short answer: no. Better to just manually apply any customizations to the new sparse config.
