### ISSUE TITLE
DKIM unsigned

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#130]
Send mail to check-auth@verifier.port25.com

It comes back with 
`DKIM check:   neutral`  
`Result:  neutral (message not signed)`  

The dkim_sign is enabled in plugins
dkim_sign.ini contains:

disabled = no
#selector = mail
#domain = example.com
headers_to_sign = From, Sender, Reply-To, Subject, Date, Message-ID, To, Cc, MIME-Version

Why then is mail not dkim signed?

**Comment by toastedmail** [comment]
`Nov 27 18:40:45 haraka haraka[2636]: [ERROR] [-] [dkim_sign] skipped: missing dkim private key`

root@smtpd:~ # cd /data/haraka/config/dkim/barontel.com/
`root@smtpd:/data/haraka/config/dkim/barontel.com # ls`
`dns             private         public          selector`

**Comment by msimerson** [comment]
Not a MT specific issue.

**Comment by toastedmail** [comment]
private was 400
chmod 444 private
still same
Nov 27 18:51:50 haraka haraka[2637]: [ERROR] [D97F669F-B447-4E89-AEB7-D7005C953139.1] [dkim_sign] skipped: missing dkim private key

**Comment by toastedmail** [comment]
It seems to me haraka cannot find it private.

**Comment by msimerson** [comment]
hint: go look at recent changes in Haraka.

**Comment by toastedmail** [comment]
In mt6 changes?
