### ISSUE TITLE
[SOLVED] provision vpopmail fails

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#131]
In the other issue where `provision vpopmail` would not complete you asked if FreeBSD was < 10.3. I answered it was originally 10.2 but upgraded to 10.3 with `freebsd-update -r 10.3-RELEASE upgrade`.  

#zfs list 
.
.
zroot/jails/base-10.2-RELEASE   282M   717G   248M  /jails/base-10.2-RELEASE

Presumably what follows below truly answers your question about FreeBSD < 10.3

root@old-mxbt1:~ # jailmanage vpopmail
Entering jail vpopmail
    /sbin/mount_nullfs /usr/ports /jails/vpopmail/usr/ports
    /sbin/mount_nullfs /var/cache/pkg /jails/vpopmail/var/cache/pkg
0 problem(s) in the installed packages found.
[root@vpopmail ~]# uname -a
**FreeBSD vpopmail 10.2-RELEASE-p24** FreeBSD 10.2-RELEASE-p24 #0: Sat Oct 22 01:03:53 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by toastedmail** [comment]
**# jailmanage vpopmail**
Entering jail vpopmail
    /sbin/mount_nullfs /usr/ports /jails/vpopmail/usr/ports
    /sbin/mount_nullfs /var/cache/pkg /jails/vpopmail/var/cache/pkg
mysql56-client-5.6.32 is vulnerable:
Remote-Code-Execution vulnerability in mysql and its variants CVE 2016-6662
WWW: https://vuxml.FreeBSD.org/freebsd/dc596a17-7a9e-11e6-b034-f0def167eeea.html

1 problem(s) in the installed packages found.
[root@vpopmail ~]# uname -a
FreeBSD vpopmail 10.3-RELEASE-p11 FreeBSD 10.3-RELEASE-p11 #0: Mon Oct 24 18:49:24 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by toastedmail** [comment]
Obviously I did something wrong when updating from 10.2 -> 10.3
`#freebsd-update -r 10.3-RELEASE upgrade  `
`#freebsd-update install `
`#shutdown -r now`
`#freebsd-update install`
`#shutdown -r now` (to be sure it boots 10.3 without any errors)
`#pkg-static upgrade -f`

**Rebuild host and base**

`# rm -f mail-toaster.sh`
`#sudo sh`
`#fetch https://raw.githubusercontent.com/msimerson/Mail-Toaster-6/master/mail-toaster.sh`
`#service jail stop`  

`#. mail-toaster.sh`  
`#provision host`  
`#provision base`  
`#service jail start`  
**Re-provision Vpopmail**
`#provision vpopmail`  
.
.
Starting jails: vpopmail.

Success! A new 'vpopmail' jail is provisioned


`

**Comment by toastedmail** [comment]
Now have:
zroot/jails/base-10.2-RELEASE   282M   716G   248M  /jails/base-10.2-RELEASE
zroot/jails/base-10.3-RELEASE   247M   716G   247M  /jails/base-10.3-RELEASE

How to safely remove the base-10.2-RELEASE ?

**Comment by msimerson** [comment]
````
zfs destroy base-10.2-RELEASE
````

**Comment by msimerson** [comment]
related to #127

**Comment by toastedmail** [comment]
Thanks for how to destroy it. Seems it has a mind of its own.

root@mxbt1:~ # zfs destroy base-10.2-RELEASE
cannot open 'base-10.2-RELEASE': dataset does not exist

root@mxbt1:/jails # ls
avg                     dns haproxy                 
mysql                   stage
base-10.2-RELEASE       dovecot haraka                  
redis                   vpopmail
base-10.3-RELEASE       dovecot.last haraka.last             
rspamd                  vpopmail.last
clamav                  geoip monitor                 
spamassassin            webmail

  # zfs destroy -r zroot/jails/base-10.2-RELEASE
cannot destroy 'zroot/jails/base-10.2-RELEASE': filesystem has dependent 
clones
use '-R' to destroy the following datasets:
zroot/jails/haproxy
zroot/jails/webmail
zroot/jails/dovecot.last
zroot/jails/rspamd
zroot/jails/mysql
zroot/jails/dns
zroot/jails/haraka.last
zroot/jails/avg
zroot/jails/vpopmail.last
zroot/jails/dovecot
zroot/jails/geoip
zroot/jails/clamav
zroot/jails/spamassassin
zroot/jails/redis

I don't think we want to destroy all the jails. Must be something like 
all the other jails still using 10.2?

Regards,
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
Lanny Baron
BaronTEL

The Future of Business Telephony Services is Here and Now!

Tel: 416.477.5411
Toll-Free: 888.241.8647
Fax: 647.693.9492
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
