### ISSUE TITLE
zfs destroy 

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#133]
As per your reply to an issue.
We had FreeBSD 10.2-RELEASE and all jails are now running 10.3-RELEASE.  Still cannot delete the base-10.2-RELEASE

` # zfs destroy base-10.2-RELEASE`  
cannot open 'base-10.2-RELEASE': dataset does not exist

` # zfs list`  
NAME                            USED  AVAIL  REFER  MOUNTPOINT
zroot                          58.3G   713G    96K  /zroot
zroot/ROOT                     2.25G   713G    96K  none
zroot/ROOT/default             2.25G   713G  2.25G  /
zroot/data                     51.7G   713G   636K  /data
zroot/data/avg                  253M   713G   253M  /data/avg
zroot/data/clamav               244M   713G   244M  /data/clamav
zroot/data/dovecot              276K   713G   276K  /data/dovecot
zroot/data/geoip               77.8M   713G  77.8M  /data/geoip
zroot/data/haproxy               96K   713G    96K  /data/haproxy
zroot/data/haraka               700K   713G   700K  /data/haraka
zroot/data/mysql               42.0M   713G  42.0M  /data/mysql
zroot/data/redis               3.75M   713G  3.75M  /data/redis
zroot/data/spamassassin         856K   713G   856K  /data/spamassassin
zroot/data/vpopmail            51.1G   713G  51.1G  /data/vpopmail
zroot/data/webmail              104K   713G   104K  /data/webmail
zroot/jails                    3.59G   713G   120K  /jails
zroot/jails/avg                 214M   713G   435M  /jails/avg
zroot/jails/avg.last            101M   713G   322M  /jails/avg.last
zroot/jails/base-10.2-RELEASE   349M   713G   252M  /jails/base-10.2-RELEASE
zroot/jails/base-10.3-RELEASE   277M   713G   248M  /jails/base-10.3-RELEASE
zroot/jails/clamav             77.0M   713G   292M  /jails/clamav
zroot/jails/clamav.last        18.4M   713G   266M  /jails/clamav.last
zroot/jails/dns                38.1M   713G   253M  /jails/dns
zroot/jails/dns.last           8.23M   713G   255M  /jails/dns.last
zroot/jails/dovecot             159M   713G   373M  /jails/dovecot
zroot/jails/dovecot.last       69.9M   713G   291M  /jails/dovecot.last
zroot/jails/geoip               138M   713G   352M  /jails/geoip
zroot/jails/geoip.last          110M   713G   357M  /jails/geoip.last
zroot/jails/haproxy            34.8M   713G   249M  /jails/haproxy
zroot/jails/haproxy.last       34.8M   713G   249M  /jails/haproxy.last
zroot/jails/haraka              230M   713G   444M  /jails/haraka
zroot/jails/haraka.last         213M   713G   460M  /jails/haraka.last
zroot/jails/monitor            95.1M   713G   310M  /jails/monitor
zroot/jails/monitor.last       91.9M   713G   317M  /jails/monitor.last
zroot/jails/mysql               121M   713G   336M  /jails/mysql
zroot/jails/mysql.last         92.8M   713G   340M  /jails/mysql.last
zroot/jails/redis              34.8M   713G   249M  /jails/redis
zroot/jails/redis.last         4.79M   713G   252M  /jails/redis.last
zroot/jails/rspamd              136M   713G   351M  /jails/rspamd
zroot/jails/rspamd.last         135M   713G   356M  /jails/rspamd.last
zroot/jails/spamassassin        107M   713G   321M  /jails/spamassassin
zroot/jails/spamassassin.last   116M   713G   330M  /jails/spamassassin.last
zroot/jails/vpopmail            162M   713G   376M  /jails/vpopmail
zroot/jails/vpopmail.last       160M   713G   381M  /jails/vpopmail.last
zroot/jails/webmail             142M   713G   356M  /jails/webmail
zroot/jails/webmail.last        205M   713G   398M  /jails/webmail.last
zroot/tmp                       252K   713G   252K  /tmp
zroot/usr                       751M   713G    96K  /usr
zroot/usr/home                   96K   713G    96K  /usr/home
zroot/usr/ports                 750M   713G   750M  /usr/ports
zroot/usr/src                    96K   713G    96K  /usr/src
zroot/var                      11.6M   713G    96K  /var
zroot/var/audit                  96K   713G    96K  /var/audit
zroot/var/crash                  96K   713G    96K  /var/crash
zroot/var/log                  3.61M   713G  3.61M  /var/log
zroot/var/mail                 7.65M   713G  7.65M  /var/mail
zroot/var/tmp                    96K   713G    96K  /var/tmp

`# zfs list -t snapshot`  
NAME                                USED  AVAIL  REFER  MOUNTPOINT
zroot/jails/base-10.2-RELEASE@p12  71.1M      -   243M  -
zroot/jails/base-10.2-RELEASE@p16  26.1M      -   252M  -
zroot/jails/base-10.2-RELEASE@p17     8K      -   252M  -
zroot/jails/base-10.3-RELEASE@p11  29.4M      -   248M  -
zroot/jails/base-10.3-RELEASE@p12   136K      -   248M  -

`# zfs destroy zroot/jails/base-10.2-RELEASE@p12`  
cannot destroy 'zroot/jails/base-10.2-RELEASE@p12': snapshot has dependent clones
use '-R' to destroy the following datasets:
zroot/jails/webmail.last

`# zfs destroy zroot/jails/base-10.2-RELEASE@p16` 
cannot destroy 'zroot/jails/base-10.2-RELEASE@p16': snapshot has dependent clones
use '-R' to destroy the following datasets:
zroot/jails/monitor.last

`# zfs destroy zroot/jails/base-10.2-RELEASE@p17`
`#`  

How would you handle this?

**Comment by msimerson** [comment]
Filesystems with a .last suffix are left around in case you need to revert. If you don't, delete them, and then the snapshots that they depend on can be deleted.

**Comment by toastedmail** [comment]
Do you read anything in closed issues?

**Comment by toastedmail** [comment]
After running
`# zfs destroy -R zroot/jails/base-10.2-RELEASE@p12`
`# zfs destroy -R zroot/jails/base-10.2-RELEASE@p16`

The only way to get rid of base-10.2-RELEASE was:
`#zfs destroy -R zroot/jails/base-10.2-RELEASE`

**Comment by msimerson** [comment]
Destroying filesystems is left as an exercise for the reader.
