### ISSUE TITLE
Make a How-To for MT6 cluster

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#137]
## Please make a How-To on building 3+ MT6 cluster where:
1) any one of 3+ servers fail, mail users are not impacted
2) no single point of failure
3) how will users connect to a single domain for smtpd and one for mx 

You made reference to pools. MT6 currently uses zfs but those zfs pools are not exported. And even if they were, the primary zfs exporting server would be a single point of failure

**Comment by msimerson** [comment]
Your job.

**Comment by toastedmail** [comment]
my job?

**Comment by toastedmail** [comment]
If it was my job and I knew how, I would write it.
