### ISSUE TITLE
haraka hostname and smtp rejection

### ISSUE THREAD

**Issue by needafix** [msimerson/Mail-Toaster-6#145]
Found emails sent out of our smtp MT6 server were being rejected. The cause is invalid HELO name (haraka). Just a suggestion, you ought to get fqdn in /etc/rc.conf in the haraka jail.

 H=smtpd.mydomain.tld (haraka) [XX.193.XXX.23]:57062 X=TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256 CV=no rejected MAIL <myfriend@her-domain.tld>: Access denied - Invalid HELO name (See RFC2821 4.1.1.1)

Once I changed /etc/rc.conf hostname= to fqdn, no mail is rejected.

**Comment by msimerson** [comment]
That's fine for you. You altered the Haraka config so that Haraka delivers directly (vs forwarding everything to qmail) so you should also alter your Haraka config to set your hostname to your FQDN. Another way is: `echo $TOASTER_HOSTNAME > /data/haraka/config/me`

**Comment by needafix** [comment]
Matt, separate MT6 servers. One for smtp and one for mx. It's not that
smtp was altered, it's because the smtp box with the vpopmail config and
domains rightly thinks mail for domain.tld belongs here.

On 2016-12-09 20:35, Matt Simerson wrote:

> That's fine for you. You altered the Haraka config so that Haraka delivers directly (vs forwarding everything to qmail) so you should also alter your Haraka config to set your hostname to your FQDN. Another way is: echo $TOASTER_HOSTNAME > /data/haraka/config/me 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/msimerson/Mail-Toaster-6/issues/145#issuecomment-266168632
[2]

**Comment by msimerson** [comment]
That's perfectly fine. Again, the right solution there is simply to configure Haraka's hostname. Your localized changes are preserved across deployments.

**Comment by needafix** [comment]
echo $TOASTER_HOSTNAME > /data/haraka/config/me
TOASTER_HOSTNAME: Undefined variable.

On 2016-12-09 20:35, Matt Simerson wrote:

> That's fine for you. You altered the Haraka config so that Haraka delivers directly (vs forwarding everything to qmail) so you should also alter your Haraka config to set your hostname to your FQDN. Another way is: echo $TOASTER_HOSTNAME > /data/haraka/config/me 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/msimerson/Mail-Toaster-6/issues/145#issuecomment-266168632
[2]

**Comment by Infern1** [comment]
echo you FQDN to config/me
