### ISSUE TITLE
Mysql provision listen

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#153]
### Expected behavior
my.cnf should be updated to not listen on all addresses

### Observed behavior
Mysql listen on all addresses, by default

### Steps to reproduce

Or listen on Jail IP, or skip the check for port 3306..

**Comment by msimerson** [comment]
The MySQL process (and **any** jailed process, for that matter) will only listen on the IPs within the jail. The only time I'd expect someone to want to alter the listening addresses is when they want MySQL to listen on an public or other IP shared with other jails. But in cases like that, wouldn't using PF rules be a better way to manage that traffic?

**Comment by Infern1** [comment]
It did notice when migrating to the new provision system and I have some other jails running, one of them is the old style mysql jail.
The provision base stopped on the listen error

`
   ***   checking for host listeners on all IPs   ***

88       mysqld     92539 26 tcp4 6 *:3306                *:*
oops!, you should not having anything listening
`

**Comment by msimerson** [comment]
I think that check in the `provision host` step? Which is why, when running `provision host`, you may need to stop your "other" jails. Then feel free to start them back up after. Or disable that check.  But either way, the global listeners **in other jails** won't affect the new jails, because they'll be on different IPs. It's only global listeners on the host itself that are problematics, because **those** listeners **may** interfere with the listeners in the jail(s).

**Comment by Infern1** [comment]
Yes it is the check in provision host. I understand why you check for listerners, just looking if we can distinguish in sockstat if it's in the jail or not

**Comment by msimerson** [comment]
> just looking if we can distinguish in sockstat if it's in the jail or not

It appears that we can, with the special jail ID of zero: `sockstat -j 0`

**Comment by Infern1** [comment]
So this would be a good addition, or add a note to the documentation, that you have to shutdown any jails with listening ports.

**Comment by msimerson** [comment]
that is already noted on the [updating](https://github.com/msimerson/Mail-Toaster-6/wiki/Updating) page.

**Comment by Infern1** [comment]
Ok, then it's just me misreading (not reading).
Closing

**Comment by msimerson** [comment]
I do agree though that it would be a good addition. The guy (me) who wrote that global listener test didn't know about that `-j 0` option when he wrote it.
