### ISSUE TITLE
Method for customization of base

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#154]
What would be the best method for customization of the base jail?

For example:
- prefer zsh over bash
- Install own .vimrc

**Comment by msimerson** [comment]
- [ ] install a "good defaults" config for zsh
- [ ] add a function for installing zsh
- [ ] add a config option for controlling zsh install
    - I'd recommend: C_SHELL="tcsh" as the default. When set to "zsh", then run the zsh install function
- [ ] add BOURNE_SHELL=sh to your mail-toaster.conf file
    - Because bash is only installed when BOURNE_SHELL=bash

**Comment by Infern1** [comment]
- I use [oh my zsh ](https://github.com/robbyrussell/oh-my-zsh) which works well, maybe a bit overhead, but love it. (first thing I tend to do on a machine)

- There is no need to install bash and zsh together from my point of view

**Comment by msimerson** [comment]
> I use oh my zsh which works well, maybe a bit overhead, but love it. (first thing I tend to do on a machine)

That's fine, just add the installer for it, and make it do what someone would expect when `C_SHELL=zsh` and/or C_SHELL=`oh_my_zsh`.

> There is no need to install bash and zsh together from my point of view

That's kinda the point of setting `BOURNE_SHELL=sh`. See the comment above for why.

**Comment by Infern1** [comment]
Making good progress with this, zsh is available as option.
Went away from oh_my_zsh since it's needs git to install and this is overhead to install from my point of view. So went for the small [prezto](https://github.com/sorin-ionescu/prezto)

However for the install to run I need to run the following code:

`setopt EXTENDED_GLOB
for rcfile in "${ZDOTDIR:-$HOME}"/.zprezto/runcoms/^README.md(.N); do
  ln -s "$rcfile" "${ZDOTDIR:-$HOME}/.${rcfile:t}"
done`

How should I run this?
tried to use 
`stage_exec setopt EXTENDED_GLOB` as a start, but this won't work. So please explain how you would do this.

**Comment by msimerson** [comment]
> I need to run the following code:

Perhaps you can explain why?  It looks to me like all that code does is populate a users $HOME directory with zsh config files. If that's the case, wouldn't it better to just drop them into /etc in the jail and have them available to every user?

**Comment by Infern1** [comment]
> Perhaps you can explain why? It looks to me like all that code does is populate a users $HOME 

Is not the case anymore solved it different now

**Comment by msimerson** [comment]
Closed by #158 and #159
