### ISSUE TITLE
Add option to share PHP between provisioned jails

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#162]
### Expected behavior
An option should make it possible to have a shared PHP provisioned jail for:

- roundcube
- rainloop
- squirellmail

Reason is, on servers with a reduced amount of RAM, you don't waste memory.

This should be option if you want independent jails this should be an option (if they are not depending on Mysql...)

**Comment by msimerson** [comment]
Thoughts on a shared PHP:

- Servers with low RAM have to make compromises (one webmail, one spam filter, one AV scanner) if they're trying to "do it all" on a single host. This really only affects VM users as hardware RAM in physical servers is now very cheap (16GB ECC for $100).
- *nix systems have mature VM implementations and when faced with memory pressure, will page inactive memory out to disk. The "wasted memory" is seldom a real issue.
- FreeBSD port dependency management
    - I expect soon a webmail port will gain PHP 7 compat and will change its dependency
    - webmails will not likely get PHP 7 compat/dependency at the same time.
- I tend to look at the webmail options as a "install one of these" choice. Most of the larger MT installs I know about have customized just one webmail and made that their MT landing page.
- Reasons for installing more than one:
    - Your name is "Matt" and you want to keep all the installers working
    - legacy users that are change adverse
    - address books aren't portable between webmail apps
        - you can export from squirrelmail and import to (at least) roundcube
    - only squirrelmail has SpamAssassin per-user prefs pane
    - only sqwebmail has maildrop configuration (future: replace with dovecot seive)

Questions:
1. In the shared PHP setup, how is the webmail PHP major version managed (5 vs 7)?
    - Are all PHP webmail jails stuck on PHP 5 until they're all PHP 7 compatible?
    - PHP 5 and PHP 7 jails?
2. How is the raft of PHP modules each webmail app needs managed?

**Comment by msimerson** [comment]
Closing, due to lack of activity.
