### ISSUE TITLE
provision dovecot stops with error

### ISSUE THREAD

**Issue by johannes73** [msimerson/Mail-Toaster-6#187]
Having used MT5 for many years, I have started to upgrade to MT6. Today I tried to reprovision the jails using the newest MT6. The provision of dovecot hangs with an error. How do I fix this...? All help very appreciated.  

### Expected behavior

provision dovecot

[...]

   ***   start jail dovecot   ***
Starting jails: dovecot.
Success! A new 'dovecot' jail is provisioned

### Observed behavior

provision dovecot

[...]

   ***   starting dovecot   ***

sysrc -R /jails/stage dovecot_enable=YES
dovecot_enable:  -> YES
sysrc -R /jails/stage dovecot_config=/data/etc/dovecot.conf
dovecot_config:  -> /data/etc/dovecot.conf
jexec stage service dovecot start
==Error==
Config file /data/etc/dovecot.conf does not exist. If this is
a new installation, please create the config files as outlined in
	# pkg info -D dovecot2
/usr/local/etc/rc.d/dovecot: WARNING: /data/etc/dovecot.conf is not readable.
/usr/local/etc/rc.d/dovecot: WARNING: failed precmd routine for dovecot

The dovecot.conf and accompanying files are in /data/dovecot/etc/...

ls /data/dovecot/etc/

conf.d				dovecot.conf
dovecot-dict-auth.conf.ext	dovecot.conf.bak
dovecot-dict-sql.conf.ext	local.conf
dovecot-ldap.conf.ext		ssl
dovecot-sql.conf.ext

**Comment by msimerson** [comment]
For some reason, it appears that /data/dovecot isn't being mounted on /jails/stage/data. That is preventing dovecot from seeing the config files in /data/etc. To troubleshoot, I just provisioned a new MT6 and then re-provisioned the dovecot jail. It worked perfectly. So it seems likely a legacy / upgrade issue that I didn't consider and compensate for.

Does your dovecot block in /etc/jail.conf look like this?

````
dovecot	{
		ip4.addr = lo1|172.16.15.15;
		mount += "/data/dovecot $path/data nullfs rw 0 0";
		mount += "/data/vpopmail $path/usr/local/vpopmail nullfs rw 0 0";
	}
````

What version of FreeBSD?
Config changes in mail-toaster.conf?  (other than host names)

**Comment by johannes73** [comment]
Thanks, Matt. I agree, this could have been an upgrade issue, since I was reprovisioning all the jails. I had no special changes in mail-toaster.conf, and used FreeBSD 10.3. I have tested again, and can not reproduce the error, so I think we should close this issue. I will revert to a brand new FreeBSD 10.3 server, and reinstall from scratch. Thanks again. I really look forward to put MT6 in production. ;-).

**Comment by msimerson** [comment]
You aren't the first (that'd be me) or the last person to upgrade a MT6 so I really do like to get to the bottom of issues like this and fix them. But that usually requires being able to reproduce it. If you do uncover any more details, please do post them there.

**Comment by johannes73** [comment]
Absolutely, I will do so... Thanks for great support, Matt. With that kind of support, MT6 is going to be the mail server of choice.
