### ISSUE TITLE
provision spamassassin fails when old ip range is used

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#190]
### Expected behavior
Coming from old style jail system, migrating my jails while keeping the same ip range (127.0.0.0 range). Fails during spamassassin install

### Observed behavior

`spamd_flags:  -> --siteconfigpath /data/etc -v -q -x -u spamd -H /var/spool/spamd -A 127.0.0.0/8 -A 127.0.0.0/12 --listen=0.0.0.0 --min-spare=3 --max-spare=6 --max-conn-per-child=25`
`jexec stage service sa-spamd start`
`Starting spamd.`
`netset: cannot include 127.0.0.0/12 as it has already been included
`

### Steps to reproduce

Set ip range to localhost range

Fixed it for now by removing 
`sysrc -j stage spamd_flags="--siteconfigpath /data/etc -v -q -x -u spamd -H /var/spool/spamd -A 127.0.0.0/8 -A $JAIL_NET_PREFIX.0$JAIL_NET_MASK --listen=0.0.0.0 --min-spare=3 --max-spare=6 --max-conn-per-child=25"`

$JAIL_NET_PREFIX, but this is not final  fix!

**Comment by msimerson** [comment]
Ahhh, right. Gotta check for that....
