### ISSUE TITLE
Provision syslog?

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#191]
### Expected behavior

I see references to a jail with with syslog, however there is not a provision-syslog.sh

**Comment by msimerson** [comment]
I started down that road, then backed out and instead use the syslog running on the host. There were a few reasons for it. I couple I'm likely forgetting but one biggie is the ability to drop a /dev/log into a jail (via it's filesystem) when it's necessary. There were a couple other issues (port bindings maybe) that I ran into and just backed out of jailing syslog.
