### ISSUE TITLE
New MT6: provision monitor fails test sending of TLS encrypted/authenticated email

### ISSUE THREAD

**Issue by johannes73** [msimerson/Mail-Toaster-6#193]
### Expected behavior

<snip>
<-  250 STARTTLS
 -> STARTTLS
<-  220 Go ahead.
=== TLS started with cipher TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256
=== TLS no local certificate set
=== TLS peer DN="/C=US/ST=Wash/L=Seat/O=TNPI/CN=imac27.simerson.net"
 ~> EHLO monitor
<~  250-haraka Hello monitor [172.16.15.11], Haraka is at your service.
<snip>

### Observed behavior

Test sending unencrypted email works. 
But sending a TLS encrypted and authenticated email fails. 

I have the full installation log, and could email it. 

From the log:

   ***   sending an email to postmaster@muttsing.com   ***

jexec stage swaks -to postmaster@muttsing.com -server 172.16.15.9 -timeout 50
=== Trying 172.16.15.9:25...
=== Connected to 172.16.15.9.
<-  220 haraka ESMTP Haraka 2.8.13 ready
 -> EHLO monitor
<-  250-haraka Hello stage [172.16.15.254], Haraka is at your service.
<-  250-PIPELINING
<-  250-8BITMIME
<-  250-SIZE 0
<-  250 STARTTLS
 -> MAIL FROM:<root@monitor>
<-  250 sender <root@monitor> OK
 -> RCPT TO:<postmaster@muttsing.com>
<-  250 recipient <postmaster@muttsing.com> OK
 -> DATA
<-  354 go ahead, make my day
 -> Date: Fri, 10 Feb 2017 19:03:01 +0100
 -> To: postmaster@muttsing.com
 -> From: root@monitor
 -> Subject: test Fri, 10 Feb 2017 19:03:01 +0100
 -> X-Mailer: swaks v20130209.0 jetmore.org/john/code/swaks/
 -> 
 -> This is a test mailing
 -> 
 -> .
<-  250 ok 1486749797 qp 91092 (BFFF7156-8EA5-490D-9975-D3E2561A634E.1)
 -> QUIT
<-  221 haraka closing connection. Have a jolly good day.
=== Connection closed with remote host.

   ***   sending a TLS encrypted and authenticated email   ***

jexec stage swaks -to postmaster@muttsing.com -server 172.16.15.9 -timeout 50 -tls -au postmaster@muttsing.com -ap *************** 
=== Trying 172.16.15.9:25...
=== Connected to 172.16.15.9.
<** 421 [F1AF6FA1-B94@haraka] connection rate limit exceeded
 -> QUIT
*** Remote host closed connection unexpectedly.

### Steps to reproduce

1. Install FreeBSD-10.3-RELEASE to server. 
2. Follow all steps on https://github.com/msimerson/Mail-Toaster-6/wiki/FreeBSD, except do not install "install CA $igned certificate", because we will use "provision letsencrypt".
3. Provision all jails, from "dns" to "monitor", including "letsencrypt".

**Comment by msimerson** [comment]
This appears to be a rate limiting issue:

````
=== Connected to 172.16.15.9.
<** 421 [F1AF6FA1-B94@haraka] connection rate limit exceeded
-> QUIT
*** Remote host closed connection unexpectedly.
````

You can either disable the rate limits (remove the `limit` plugin from /data/haraka/config/plugins and restart Haraka) or wait a few minutes and try again.

**Comment by johannes73** [comment]
Thank you, Matt. 

I have:
1. put a # in front of the line "limit" in the file /data/haraka/config/plugins, 
2. restarted the haraka jail.
3. provisioned monitor again. 

4. haraka did not want to accept the test email, because of bad karma, I guess because I have tested a few times:
"<** 554 [322E2F70-3FA@haraka] very bad karma score: -8"
5. jexec redis redis
6. select 3
7. keys *
8. del "karma|172.16.15.254"
9. exit

10. provisioned monitor again. 

Now it works. 

A couple of thoughts:
Maybe limit (point 1) could be removed from the default install?
Is there a way of not causing bad karma when testing (to avoid steps 4-9)?

Thanks again.

**Comment by johannes73** [comment]
Works great now. Thank you, Matt.
