### ISSUE TITLE
Webmail/IMAP does not show user folders after migration MT5 -> MT6 - proposed solution

### ISSUE THREAD

**Issue by johannes73** [msimerson/Mail-Toaster-6#201]
### Expected behavior

Server was migrated from MT5 (with Courier IMAP) to MT6 (with dovecot IMAP). After user logs into webmail, his manually created folders should still be there. 

### Observed behavior

The folders do not show up in the user webmail. 

### Steps to reproduce

Install FreeBSD-10.3 + MT6. 
Migrate from MT5 to MT6 according to migration instructions on Github (rsync of files, and vpopmail data).

### Solution that works - not sure how to integrate this info in the MT6 default installation

1. I found a page that deals with migration from courierimap to dovecot imap: http://wiki.dovecot.org/Migration/Courier

2. Downloaded the script courier-dovecot-migrate.pl, and put it in the dovecot jail.

3. Tested, dry run:
`root@dovecot:/usr/local/bin # ./courier-dovecot-migrate.pl --to-dovecot --recursive /usr/local/vpopmail/domains/`

4. Ran with "--convert --overwrite":
`root@dovecot:/usr/local/bin # ./courier-dovecot-migrate.pl --to-dovecot --convert --overwrite --recursive /usr/local/vpopmail/domains/`

5. It worked. Now user folders show up in webmail. 

I am not sure, maybe this is already included in the MT6 installation scripts, and I might have missed to do this during installation. If it is not included in the MT6 default install, maybe it could somehow be included as an option, or in the migration instructions page? Thanks again.

**Comment by msimerson** [comment]
It is not in the MT6 build instructions.

I converted from courier to dovecot many years before MT6 and there's a [Migrating to Dovecot](https://www.tnpi.net/wiki/Migrating_to_Dovecot) page on the MT5 wiki. 

This comment on the dovecot wiki page is concerning:

> The --recursive option goes through only one level down in directory hierarchies. This means that if you have some kind of a directory hashing scheme (or even domain/username/), it won't convert all of the files.

For anyone with more than N (I forget the #) users, they will have users in subdirs and that script won't fix it for them. Maybe adding a link to the old migrating page and this issue on the Upgrading page would be the right thing?

**Comment by johannes73** [comment]
Aha, yes, that sounds like a good solution. Thank you, Matt. 

/ Johannes

**Comment by msimerson** [comment]
I've updated [Updating](https://github.com/msimerson/Mail-Toaster-6/wiki/Updating)
