### ISSUE TITLE
Strange log from Haraka

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#205]
### Observed behavior

Not sure if this is wrong or normal behavior, seeing this frequently in the logs:

`[ERROR] [-] [core] backend failure: 127.0.0.8:25 - B84E3B7F-4CED-49AC-87B6-2956796BCB21: [127.0.0.8:25] SMTP connection timed out`

`[ERROR] [-] [core] backend failure: 127.0.0.8:25 - 73FB5B3A-9003-4010-B7B6-7260E96E4DC2: [127.0.0.8:25] SMTP connection timed out`

`[ERROR] [-] [core] backend failure: 127.0.0.8:25 - 73FB5B3A-9003-4010-B7B6-7260E96E4DC2: [127.0.0.8:25] SMTP connection timed out
`
As indication
`#grep 'SMTP connection timed out' /var/log/haraka.log|wc -l
     932`

**Comment by msimerson** [comment]
It's a mostly harmless error (the only damage is wasted disk space). I've tested haraka/Haraka#1842 locally and it fixes the issue for me. Can you test and confirm as well?
