### ISSUE TITLE
swap_pager_getswapspace(16): failed

### ISSUE THREAD

**Issue by needafix** [msimerson/Mail-Toaster-6#209]
Hi Matt,
For some reason one of our Mail-Toaster-6 Servers had issue with: swap_pager_getswapspace(16): failed

This is a very lightly used server. However top shows:

 PID TT  STAT     TIME COMMAND
  12  -  WL    0:04.10 [intr]
 129  -  IWs   0:00.00 adjkerntz -i
 769  -  IWs   0:00.00 sendmail: Queue runner@00:30:00 for /var/spool/clientmqueue (sendmail)
1031  -  IWsJ  0:00.00 /bin/sh /usr/local/bin/mysqld_safe --defaults-extra-file=/var/db/mysql/my.cnf --user=mysql --datadir
1306  -  IWJ   0:00.00 /usr/local/bin/tcpserver -H -R -c10 -u 89 -g 82 -x /usr/local/vpopmail/etc/tcp.smtp.cdb 0.0.0.0 25 /
1316  -  IWJ   0:00.00 /bin/sh ./run
1317  -  IWJ   0:00.00 /usr/local/bin/perl -Tw /usr/local/bin/qmail-deliverabled -f
1319  -  IWJ   0:00.00 /bin/sh ./run
1322  -  IWJ   0:00.00 /usr/local/bin/tcpserver -vHRD 0.0.0.0 89 /usr/local/vpopmail/bin/vpopmaild
1489  -  IWsJ  0:00.00 /usr/local/sbin/dovecot -c /data/etc/dovecot.conf
1491  -  IWJ   0:00.00 anvil: [0 connections] (anvil)
1492  -  IWJ   0:00.00 dovecot/log
1495  -  IWJ   0:00.00 dovecot/config
2234  -  IWsJ  0:00.00 rspamd: main process (rspamd-1.3.5)

Is /bin/sh ./run a Mail-Toaster process ?

If it is, can you let me know how to increase swap in this zfs Mail-Toaster system.
Thanks Matt

**Comment by msimerson** [comment]
Your system is out of memory. Add or more memory or disable / shut down stuff that uses memory. You're the sysadmin, so go administer the system.

**Comment by needafix** [comment]
Hi Matt, 

Yes I definitely understand servers. Should after 18 years. 

The Server is not out of available memory. A process or processes are
robbing the server of its memory. Without doing a thing, it returned
back to normal. What I wanted to find out from you is, how to really
find the culprit. 

last pid: 52373; load averages: 0.18, 0.26, 0.24 

Thanks. 

On 2017-03-22 23:12, Matt Simerson wrote:

> Your system is out of memory. Add or more memory or disable / shut down stuff that uses memory. You're the sysadmin, so go administer the system. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/msimerson/Mail-Toaster-6/issues/209#issuecomment-288605299
[2]
