### ISSUE TITLE
Messages from roundcube sometimes denied

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#214]
### Expected behavior
No message in the log

### Observed behavior

Seeing this in my Haraka log when sending a message:

`[access] fail:invalid domain: roundcube, invalid domain: roundcube`

Not sure if this is the result some clients report mail from roundcube is not send.
Not able to reproduce myself at the moment

**Comment by msimerson** [comment]
roundcube is an invalid domain. Configure the hostname to instead be roundcube.[yourhostname.com].

**Comment by msimerson** [comment]
more precisely, add roundcube.[yourdomain.com] to /data/dns/unbound.conf.local. If that file doesn't exist, create it. After populating it, reprovision the dns jail.

**Comment by Infern1** [comment]
Yes agree, can we somehow automate this?

**Comment by msimerson** [comment]
Surely. But then, what domains to insert? That's a rather local choice. The domain I use for most of the jails doesn't exist in my mail-toaster.conf.

**Comment by Infern1** [comment]
Would it be an option to set this hostname in the mail-toaster.conf ?

**Comment by msimerson** [comment]
I'm pretty sure this issue is now resolved by [a karma update](https://github.com/haraka/haraka-plugin-karma/pull/27) that exempts RFC 1918 IPs from scoring. Reopen if this recurs.
