### ISSUE TITLE
correct syntax for adding dns to /etc/jail.conf

### ISSUE THREAD

**Issue by needafix** [msimerson/Mail-Toaster-6#217]
Although there is no dns in /data   added the following to /etc/jail.conf Please let us know if this is the correct syntax;

dns     {
                ip4.addr = lo1|172.16.15.3;
                **mount+= "/data/dns $path/data nullfs rw 0 0";**
        }

Thanks

**Comment by msimerson** [comment]
Yes, that's correct.
