### ISSUE TITLE
Roundcube connection failed after upgrading webmail and roundcube jails

### ISSUE THREAD

**Issue by needafix** [msimerson/Mail-Toaster-6#221]
After running provision webmail and provision roundcube, roundcube is unable to connect to db.

DB Error in /usr/local/www/roundcube/program/lib/Roundcube/rcube_db.php (173): SQLSTATE[HY000] [1045] Access denied for user 'roundcube'@'roundcube' (using password: YES)
DB Error: SQLSTATE[HY000] [1045] Access denied for user 'roundcube'@'roundcube' (using password: YES)
DATABASE ERROR: CONNECTION FAILED!

Tried using our config.inc.php in /jails/roundcube/usr/local/www/roundcube/config which did not work either. 
Tried changing password for roundcube in mysql, that did not work either.

Using qmailadmin has no issues for any user.
Thanks for any help,

**Comment by Infern1** [comment]
probably mysql is unable resolve roundcube host
Check `ping roundcube` on the mysql jail

**Comment by needafix** [comment]
I assume you meant to jailmanage mysql  if so, cannot ping period.

root@mysql:~ # ping roundcube
ping: socket: Operation not permitted

Can ping roundcube on the mt6 server itself just not in any jail

 # ping roundcube
PING roundcube (172.16.15.33): 56 data bytes
64 bytes from 172.16.15.33: icmp_seq=0 ttl=64 time=0.041 ms

**Comment by msimerson** [comment]
ICMP is blocked in jails by default. A better and more thorough test is to use the mysql client in the roundcube jail to connect to mysql in it's jail.

**Comment by needafix** [comment]
The following is in /jails/roundcube/usr/local/www/roundcube/config/config.inc.php

mysql://roundcube:b0bba5c86f1d640481d01546aef11ee81471@172.16.15.4/roundcubemail'

   # jailmanage mysql
root@mysql:~ # mysql -u roundcube -p
Enter password:
ERROR 1045 (28000): Access denied for user 'roundcube'@'localhost' (using password: YES)

used passwd from above mysql:  line

**Comment by needafix** [comment]
Tried to # provision roundcube
stops at:
 ***   preserving /jails/stage//usr/local/www/roundcube/config/config.inc.php   ***

cp: 34826ZFS_JAIL_MNT/roundcube.last//usr/local/www/roundcube/config/config.inc.php: No such file or directory
#

**Comment by needafix** [comment]
Is there a any fix for provision roundcube?

**Comment by needafix** [comment]
Infern1 **you were 100% correct**. 
Mysql db had roundcube as roundcube@172.16.15.10. But now roundcube jail has IP of 172.16.15.33

I don't know why msimerson could not simply write something to the effect of: 
**jexec mysql mysql**
**use mysql;**
**rename user roundcube@172.16.15.10 to roundcube@172.16.15.33;**
exit
Thing is msimerson builds this pretty well all inclusive mail system which is designed for people without his skill set. 6 days pass by and no one could get to roundcube!
