### ISSUE TITLE
Duplicate inbound email

### ISSUE THREAD

**Issue by needafix** [msimerson/Mail-Toaster-6#223]
Hi, what might be causing duplicate inbound email and how to fix it?
Thank you.

Example:
**Headers from 1st email**:
Received: (qmail 34132 invoked by uid 89); 11 May 2017 12:48:53 -0000
Received: from unknown (HELO host1.domain.tld) (172.16.15.9)
  by vpopmail with SMTP; 11 May 2017 12:48:53 -0000
Authentication-Results: host1.domain.tld; iprev=pass; spf=pass smtp.mailfrom=otherdomain.tld; dkim=pass header.i=@otherdomain.tld.20150623.gappssmtp.com
Received-SPF: Pass (host1.domain.tld: domain of otherdomain.tld designates 209.85.128.196 as permitted sender) receiver=host1.domain.tld; identity=mailfrom; client-ip=209.85.128.196; helo=mail-wr0-f196.google.com; envelope-from=<sales@otherdomain.tld>
Received-SPF: None (host1.domain.tld: domain of mail-wr0-f196.google.com does not designate 209.85.128.196 as permitted sender) receiver=host1.domain.tld; identity=helo; client-ip=209.85.128.196; helo=mail-wr0-f196.google.com; envelope-from=<sales@otherdomain.tld>
Received: from mail-wr0-f196.google.com (mail-wr0-f196.google.com [209.85.128.196])
        by host1.domain.tld (Haraka/2.8.13) with ESMTPS id 5F383AC5-136D-495E-A141-5FFE2A39A42F.1
        envelope-from <sales@otherdomain.tld>
        (version=TLSv1/SSLv3 cipher=ECDHE-RSA-AES128-GCM-SHA256 verify=FAIL);
        Thu, 11 May 2017 08:48:49 -0400
Received: by mail-wr0-f196.google.com with SMTP id g12so3427082wrg.2
        for <paul.james@cybertouch.org>; Thu, 11 May 2017 05:48:49 -0700 (PDT)
**Message-ID: <746f0b7b22ad55e1d33b3a9e042db245@www.otherdomain.tld>**

**Headers from 2nd email**:

From sales@otherdomain.tld Thu May 11 12:48:53 2017
Return-Path: <sales@otherdomain.tld>
Delivered-To: domain.tld=user@domain.tld
Received: (qmail 34132 invoked by uid 89); 11 May 2017 12:48:53 -0000
Received: from unknown (HELO host1.domain.tld) (172.16.15.9)
  by vpopmail with SMTP; 11 May 2017 12:48:53 -0000
Authentication-Results: host1.domain.tld; iprev=pass; spf=pass smtp.mailfrom=otherdomain.tld; dkim=pass header.i=@otherdomain.tld.20150623.gappssmtp.com
Received-SPF: Pass (host1.domain.tld: domain of otherdomain.tld designates 209.85.128.196 as permitted sender) receiver=host1.domain.tld; identity=mailfrom; client-ip=209.85.128.196; helo=mail-wr0-f196.google.com; envelope-from=<sales@otherdomain.tld>
Received-SPF: None (host1.domain.tld: domain of mail-wr0-f196.google.com does not designate 209.85.128.196 as permitted sender) receiver=host1.domain.tld; identity=helo; client-ip=209.85.128.196; helo=mail-wr0-f196.google.com; envelope-from=<sales@otherdomain.tld>
Received: from mail-wr0-f196.google.com (mail-wr0-f196.google.com [209.85.128.196])
        by host1.domain.tld (Haraka/2.8.13) with ESMTPS id 5F383AC5-136D-495E-A141-5FFE2A39A42F.1
        envelope-from <sales@otherdomain.tld>
        (version=TLSv1/SSLv3 cipher=ECDHE-RSA-AES128-GCM-SHA256 verify=FAIL);
        Thu, 11 May 2017 08:48:49 -0400
Received: by mail-wr0-f196.google.com with SMTP id g12so3427082wrg.2
        for <user@domain.tld>; Thu, 11 May 2017 05:48:49 -0700 (PDT)
**Message-ID: <746f0b7b22ad55e1d33b3a9e042db245@www.otherdomain.tld>**

**Comment by needafix** [comment]
Hello, again, what might be causing what appears to be duplicate email ?  Just received duplicate email but grep on the sending domain shows only one email received. Qmailadmin shows standard routing for the email account. Please, what might be the cause of duplicates in Thunderbird and Roundcube?
Thanks.

**Comment by msimerson** [comment]
The times when I've seen this were because there was duplicate delivery lines in a .qmail file for that user.

**Comment by needafix** [comment]
Would the following be the cause in users .qmail

|preline /usr/local/bin/maildrop /etc/mailfilter
| /usr/local/bin/maildrop /usr/local/etc/mail/mailfilter

**Comment by needafix** [comment]
Thank you, 
.qmail should only contain: |preline /usr/local/bin/maildrop /etc/mailfilter
