### ISSUE TITLE
Disable inbound unencrypted mail

### ISSUE THREAD

**Issue by rduffner** [msimerson/Mail-Toaster-6#225]
A coworker mentioned that he has done this on his mailserver (with postfix).

Apparently, it eliminated a lot of spam because most spam-zombies can't be bothered to implement a TLS SMTP client.

I looked into the documentation of haraka but couldn't figure it out.

I have an older toaster anyway - come FreeBSD 11.1, I'll redo.

**Comment by msimerson** [comment]
You could do this with Haraka and a custom plugin. Have it run on the MAIL_FROM hook and check if the connection is secure or not. If not, terminate the connection.

I haven't looked at my mails to see what I'd lose by trashing non-TLS connections but I'd bet it would cost some valid mails.

**Comment by msimerson** [comment]
If you decide to implement this (or hire someone to), I'd recommend creating a NPM packaged plugin named something such as `haraka-plugin-tls-required`. I'd also suggest including some type of support for whitelisting. It seems inevitable that someone you want to get mail from doesn't have working TLS yet. On the flip side, I'd also add a strict validation mode that requires TLS chain validation for Well Known Senders (gmail, hotmail, etc.).

**Comment by msimerson** [comment]
Another way to do this would be extending karma with TLS rules. If you make to the MAIL FROM hook without negotiating TLS, you get a karma award (from points to disconnect).

**Comment by msimerson** [comment]
I just did a quick search (`conn.count.msg.accept:[1 TO *] AND p.karma.score:[* TO 0] AND !(_exists_:p.tls.cipher.name)` of my mail traffic to see the impact. In the past week, this rule would have blocked 26% of ham messages from delivery. Of that 26%, the majority are marketing (travelocity, wayfair, jc penney, other retailers) and lots of users want those messages.

**Comment by msimerson** [comment]
There's a [karma pull request](https://github.com/haraka/haraka-plugin-karma/pull/19) for this now.
