### ISSUE TITLE
provision roundcube doesn't complete

### ISSUE THREAD

**Issue by needafix** [msimerson/Mail-Toaster-6#226]
sudo sh
fetch https://raw.githubusercontent.com/msimerson/Mail-Toaster-6/master/mail-toaster.sh
. mail-toaster.sh
service jail stop
provision host
service jail start
provision base
provision webmail
provision roundcube
.
.
.
   ***   starting nginx   ***

sysrc -R /jails/stage nginx_enable=YES
nginx_enable:  -> YES
jexec stage service nginx start
Performing sanity check on nginx configuration:
**nginx: [emerg] open() "/data/etc/nginx.conf" failed (2: No such file or directory)**
**nginx: configuration file /data/etc/nginx.conf test failed**
Starting nginx.
**nginx: [emerg] open() "/data/etc/nginx.conf" failed (2: No such file or directory)**
/usr/local/etc/rc.d/nginx: WARNING: failed to start nginx
 ***   testing PHP FPM (FastCGI Process Manager) is running   ***

checking for process php-fpm in staged jail
42656
42655
42654

   ***   testing PHP FPM is listening   ***

   ***   testing nginx is running   ***

**checking for process nginx in staged jail**

**Comment by needafix** [comment]
Matt, any idea how to get provision roundcube working?
Thanks,

**Comment by needafix** [comment]
Temporary fix to get roundcube working whilst Matt fixes his scripts:
  After one sees the following whilst running #  provision roundcube
nginx: [emerg] open() "/data/etc/nginx.conf" failed (2: No such file or directory)
nginx: configuration file /data/etc/nginx.conf test failed
Starting nginx.
nginx: [emerg] open() "/data/etc/nginx.conf" failed (2: No such file or directory)

Followed by last line: **checking for process nginx in staged jail**

Type: **exit**  (assuming you originally ran sudo sh)

Now stop the stage jail: **service jail stop stage**
rename the stage jail to roundcube
**zfs rename zfsroot/jails/stage zfsroot/jails/roundcube**
make sure it worked: **zfs list**
zroot/jails/roundcube          91.7M   715G   323M  /jails/roundcube  

Start the roundcube jail: service jail start roundcube

I have items in the config DIR in /data/roundcube/config which need to be in the roundcube jail. You may not. If you do, run the following: rsync -a /data/roundcube/config/ /jails/roundcube/config/

You should now be able to use roundcube. If you run provision roundcube again, it will fail with same issue as above. We need to wait for Matt to fix scripts.

**Comment by msimerson** [comment]
> I have items in the config DIR in /data/roundcube/config which need to be in the roundcube jail. You may not.

Perhaps the issue is that **you** need to change the scripts to accommodate your local changes. Since it's a change that matters to you, create a PR that implements the feature.
