### ISSUE TITLE
New MT6 on new FreeBSD 11.0 VM installs perfectly. Why provision upgrades problematic on existing VM

### ISSUE THREAD

**Issue by needafix** [msimerson/Mail-Toaster-6#229]
Since running provision roundcube fails and provision webmail completes but the dropdown list is missing rainloop and sqwebmail on existing FreeBSD 10.3 VM, built new **FreeBSD 11.0 VM** and install MT6.

**All jails installed without any hiccup**.

The question then is, what might be causing upgrades to fail on an existing MT6 Server running on FreeBSD 10.3?
Thanks.

**Comment by msimerson** [comment]
You.

**Comment by needafix** [comment]
If the issue of failing is 'you', perhaps you can enlighten me as its your instructions being followed.
The fact is, just following upgrade instructions shown on https://github.com/msimerson/Mail-Toaster-6/wiki/Updating

**Comment by msimerson** [comment]
I don't have that problem and you do. I don't know why, that's for you, the system administrator, the figure out.

**Comment by needafix** [comment]
Matt, as you've said MT6 is a turnkey system for mail. In fact all the
previous iterations of Mail Toaster has been that way. 

IIRC, to use webmail, the client has to point browser to mt6 fqdn and
after selecting the mail client, like roundcube, they login as
username@domain.tld.  

I wanted to offer them the ability to go to mail.thierdomainname.tld and
login with just username without domain name. 

In order to accomplish this, the following change has to be made to
/jails/haproxy/etc/haproxy.conf

> frontend http-in
> bind *:80
> bind *:443 ssl crt-list /etc/ssl/private/crt-list.txt
> #bind *:443 ssl crt /etc/ssl/private

And the domainname.pem files have to exist in
/jails/haproxy/etc/ssl/private 

Also needed is 'mail.domain.tld.inc.php for each domain in
/jails/roundcube/usr/local/www/roundcube/config/ 

I assume because of the changes/additions listed above it is breaking
MT6 

Perhaps you know of another way of accomplishing having users go to
http://mail.theirdomain.tld and logging in with just their $username /
pass 

Thanks.

On 2017-06-12 14:01, Matt Simerson wrote:

> I don't have that problem and you do. I don't know why, that's for you, the system administrator, the figure out. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/msimerson/Mail-Toaster-6/issues/229#issuecomment-307869053
[2]

**Comment by msimerson** [comment]
> In fact all the previous iterations of Mail Toaster has been that way.

Not a fact. I'm the guy who got the calls when folks tried to upgrade previous versions of Mail Toaster. I consider that the achilles heel of previous versions of Mail Toaster. From invalid assumptions flow invalid conclusions.

**Comment by needafix** [comment]
Perhaps I was not clear. What I meant was your Mail Toaster has been a
turn key mail system for multiple domains. I understand the PITA of
getting phones calls for support. 

On 2017-06-12 18:21, Matt Simerson wrote:

>> In fact all the previous iterations of Mail Toaster has been that way.
> 
> Not a fact. I'm the guy who got the calls when folks tried to upgrade previous versions of Mail Toaster. I consider that the achilles heel of previous versions of Mail Toaster. From invalid assumptions flow invalid conclusions. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/msimerson/Mail-Toaster-6/issues/229#issuecomment-307950577
[2]

**Comment by msimerson** [comment]
> What I meant was your Mail Toaster has been a turn key mail system for multiple domains.

It still is. It's been a turn key fairly easy to install system for decades. But it has also always been challenging to upgrade without breaking mail.
