### ISSUE TITLE
provision haraka fails to build

### ISSUE THREAD

**Issue by s571** [msimerson/Mail-Toaster-6#234]
Fresh install of MT6 on FreeBSD 11.0 VM.
When running # provision haraka
it fails to complete at:

[INFO] [-] [core] Loading plugin: karma
[NOTICE] [-] [core] the haraka-plugin- prefix is not required in config/plugins
[CRIT] [-] [core] TypeError: Cannot read property 'notes' of undefined
[CRIT] [-] [core]     at Plugin.exports.register (/usr/local/lib/node_modules/Haraka/node_modules/haraka-plugin-karma/index.js:33:16)
[CRIT] [-] [core]     at Object.plugins._register_plugin (/usr/local/lib/node_modules/Haraka/plugins.js:373:12)
[CRIT] [-] [core]     at Object.plugins.load_plugin (/usr/local/lib/node_modules/Haraka/plugins.js:346:17)
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/plugins.js:318:17
[CRIT] [-] [core]     at Array.forEach (native)
[CRIT] [-] [core]     at Object.plugins.load_plugins (/usr/local/lib/node_modules/Haraka/plugins.js:317:17)
[CRIT] [-] [core]     at Object.Server.createServer (/usr/local/lib/node_modules/Haraka/server.js:266:20)
[CRIT] [-] [core]     at Object.<anonymous> (/usr/local/lib/node_modules/Haraka/haraka.js:76:8)
[CRIT] [-] [core]     at Module._compile (module.js:571:32)
[CRIT] [-] [core]     at Object.Module._extensions..js (module.js:580:10)
[NOTICE] [-] [core] Shutting down
#

**Comment by s571** [comment]
Try again. Destroy VM
Create new FreeBSD 11.0 VM
pkg install -y sudo
edit sshd_config for listen address (public/private) restart sshd
. mail-toaster.sh && provision host: both successful
provision base: **Success! A new 'base' jail is provisioned**
provision dns: **Success! A new 'dns' jail is provisioned**
**switching host resolver to 172.16.15.3**
provision mysql: **Success! A new 'mysql' jail is provisioned**
provision redis: **Success! A new 'redis' jail is provisioned**
provision clamav: **Success! A new 'clamav' jail is provisioned**
provision avg: **Success! A new 'avg' jail is provisioned**
provision geoip: **Success! A new 'geoip' jail is provisioned**
provision spamassassin: **Success! A new 'spamassassin' jail is provisioned**
provision rspamd: **Success! A new 'rspamd' jail is provisioned**
provision vpopmail: **Success! A new 'vpopmail' jail is provisioned**
provision dovecot: **Success! A new 'dovecot' jail is provisioned**
provision haraka: [INFO] [-] [core] Loading plugin: karma
[NOTICE] [-] [core] the haraka-plugin- prefix is not required in config/plugins
[CRIT] [-] [core] TypeError: Cannot read property 'notes' of undefined
[CRIT] [-] [core]     at Plugin.exports.register (/usr/local/lib/node_modules/Haraka/node_modules/haraka-plugin-karma/index.js:33:16)
[CRIT] [-] [core]     at Object.plugins._register_plugin (/usr/local/lib/node_modules/Haraka/plugins.js:373:12)
[CRIT] [-] [core]     at Object.plugins.load_plugin (/usr/local/lib/node_modules/Haraka/plugins.js:346:17)
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/plugins.js:318:17
[CRIT] [-] [core]     at Array.forEach (native)
[CRIT] [-] [core]     at Object.plugins.load_plugins (/usr/local/lib/node_modules/Haraka/plugins.js:317:17)
[CRIT] [-] [core]     at Object.Server.createServer (/usr/local/lib/node_modules/Haraka/server.js:266:20)
[CRIT] [-] [core]     at Object.<anonymous> (/usr/local/lib/node_modules/Haraka/haraka.js:76:8)
[CRIT] [-] [core]     at Module._compile (module.js:571:32)
[CRIT] [-] [core]     at Object.Module._extensions..js (module.js:580:10)
[NOTICE] [-] [core] Shutting down
#

**Comment by s571** [comment]
The original build of the VM = 15GB
Retrying with a 25GB VM

**Comment by s571** [comment]
Tried rebuilding with 40GB FreeBSD 11.0 VM, fails with same as above

`# provision haraka`
[NOTICE] [-] [core] the haraka-plugin- prefix is not required in config/plugins
[CRIT] [-] [core] TypeError: Cannot read property 'notes' of undefined
[CRIT] [-] [core]     at Plugin.exports.register (/usr/local/lib/node_modules/Haraka/node_modules/haraka-plugin-karma/index.js:33:16)
[CRIT] [-] [core]     at Object.plugins._register_plugin (/usr/local/lib/node_modules/Haraka/plugins.js:373:12)
[CRIT] [-] [core]     at Object.plugins.load_plugin (/usr/local/lib/node_modules/Haraka/plugins.js:346:17)
[CRIT] [-] [core]     at /usr/local/lib/node_modules/Haraka/plugins.js:318:17
[CRIT] [-] [core]     at Array.forEach (native)
[CRIT] [-] [core]     at Object.plugins.load_plugins (/usr/local/lib/node_modules/Haraka/plugins.js:317:17)
[CRIT] [-] [core]     at Object.Server.createServer (/usr/local/lib/node_modules/Haraka/server.js:266:20)
[CRIT] [-] [core]     at Object.<anonymous> (/usr/local/lib/node_modules/Haraka/haraka.js:76:8)
[CRIT] [-] [core]     at Module._compile (module.js:571:32)
[CRIT] [-] [core]     at Object.Module._extensions..js (module.js:580:10)
[NOTICE] [-] [core] Shutting down
`#`

**Comment by s571** [comment]
Tried on a 40GB VM, same - provision haraka fails.

**Comment by msimerson** [comment]
This was fixed by haraka/haraka-resultes#8

**Comment by s571** [comment]
If it was fixed, how is it provision haraka is failing on a fresh installation?

**Comment by msimerson** [comment]
Try again now. It's working for me.

**Comment by s571** [comment]
jail -r haraka

   ***   zroot/data/haraka filesystem exists   ***

zfs rename zroot/jails/haraka.ready zroot/jails/haraka

   ***   adding haraka to /etc/jail.conf   ***


haraka  {
                ip4.addr = lo1|172.16.15.9;

                devfs_ruleset = 7;
                mount += "/data/haraka $path/data nullfs rw 0 0";
                mount += "/data/avg $path/data/avg nullfs rw 0 0";
                mount += "/data/geoip $path/usr/local/share/GeoIP nullfs ro 0 0";
        }

   ***   service jail start haraka   ***

Starting jails: haraka.

Success! A new 'haraka' jail is provisioned
