### ISSUE TITLE
mail_from.access 

### ISSUE THREAD

**Issue by s571** [msimerson/Mail-Toaster-6#237]
munin@monitor was constantly getting -8 karma score. Added munin@monitor to mail_from.access.whitelist and subsequent mail from this address was delivered normally.

After seeing 2 successful deliveries from munin@monitor decided to remove munin@monitor from the whitelist and add it to the mail_from.access.blacklist. Mail from munin@monitor is still being delivered.

Question is, is there perhaps a time before haraka or karma will use the mail_from.access.blacklist?
Thanks

**Comment by msimerson** [comment]
The issue has nothing to do with the blacklist. karma treats messages from unknown senders more strictly than senders that we've received mail from in the past.

**Comment by s571** [comment]
Hate to argue but isn't the purpose of mail_from.access.blacklist 
supposed to block email addresses such as munin@monitor ? No need for 
tons of mail to fill up postmaster. Not blaming karma. I thought its the 
job of haraka.

**Comment by msimerson** [comment]
Yeah, blacklist should block it **always** and if it doesn't, that's a bug.

**Comment by s571** [comment]
It might be the case I am not understanding how the access files work. 
It seems from what I read in haraka -h access, access.domain add domain 
name and its blocked, !domain.name and mail is accepted. 
mail_from.access whitelist/blacklist is for email addresses allow/block.

Is that correct?
Thanks.

**Comment by msimerson** [comment]
Yes, that's mostly correct. However, it's more correct to think that access is for denying access (blacklisting), and whitelisting was added because sometimes blacklists are too wide (ie, I want to blacklist aol.com except for friend@aol.com). I use access.domains primarily for influencing karma scoring.

**Comment by s571** [comment]
Hi, here is the info:

# cat /data/haraka/config/mail_from.access.blacklist
mail@messaging.zoosk.com
munin@monitor


# tail -f /var/log/maillog
Jul 14 14:30:00 haraka haraka[97119]: [NOTICE] 
[182AFF70-1147-4E30-888E-E1E3D624A056] [core] connect ip=172.16.15.11 
port=29825 local_ip=172.16.15.9 local_port=25
Jul 14 14:30:01 dovecot dovecot: pop3-login: Login: 
user=<support@barontel.com>, method=CRAM-MD5, rip=104.193.49.17, 
lip=172.16.15.15, mpid=49260, TLS, session=<7ta2PEtUnM5owTER>
Jul 14 14:30:01 dovecot dovecot: pop3(support@barontel.com): 
Disconnected: Logged out top=0/0, retr=0/0, del=0/0, size=0
Jul 14 14:30:08 haraka haraka[97119]: [NOTICE] 
[182AFF70-1147-4E30-888E-E1E3D624A056.1] [core] sender <munin@monitor> 
code=CONT msg=""
Jul 14 14:30:08 haraka haraka[97119]: [NOTICE] 
[182AFF70-1147-4E30-888E-E1E3D624A056.1] [core] recipient 
<postmaster@barontel.com> code=OK msg="" sender="munin@monitor"
Jul 14 14:30:09 clamav clamd[95999]: SelfCheck: Database status OK.
Jul 14 14:30:09 spamassassin spamd[41889]: spamd: connection from haraka 
[172.16.15.9]:16791 to port 783, fd 5
Jul 14 14:30:09 spamassassin spamd[41889]: spamd: checking message 
(unknown) for postmaster@barontel.com:58
Jul 14 14:30:09 haraka haraka[97122]: [NOTICE] 
[4F7D7A0A-5590-42CF-AD50-BC5982C5E6DA] [core] connect ip=170.130.143.175 
port=59038 local_ip=172.16.15.9 local_port=25
Jul 14 14:30:09 haraka haraka[97119]: [ERROR] [-] [core] backend 
failure: 172.16.15.8:25 - 1D05F6D2-E5AB-4783-A111-87662E542198: 
[172.16.15.8:25] SMTP connection timed out
Jul 14 14:30:09 spamassassin spamd[41889]: spamd: clean message 
(0.4/5.0) for postmaster@barontel.com:58 in 0.6 seconds, 872 bytes.
Jul 14 14:30:09 spamassassin spamd[41889]: spamd: result: . 0 - 
ALL_TRUSTED,MISSING_MID,TO_MALFORMED 
scantime=0.6,size=872,user=postmaster@barontel.com,uid=58,required_score=5.0,rhost=haraka,raddr=172.16.15.9,rport=16791,mid=(unknown),autolearn=no 
autolearn_force=no
Jul 14 14:30:09 haraka haraka[97119]: [NOTICE] 
[182AFF70-1147-4E30-888E-E1E3D624A056.1] [core] message mid="" size=580 
rcpts=1/0/0 delay=0.577 code=CONT msg=""
Jul 14 14:30:09 haraka haraka[97119]: [ERROR] [-] [core] 
client.socket.remoteAddress undefined!
Jul 14 14:30:09 vpopmail qmail: 1500057009.945073 new msg 29963
Jul 14 14:30:09 vpopmail qmail: 1500057009.945136 info msg 29963: bytes 
1317 from <munin@monitor> qp 49264 uid 89
Jul 14 14:30:09 haraka haraka[97119]: [NOTICE] 
[182AFF70-1147-4E30-888E-E1E3D624A056.1] [core] queue code=OK msg="ok 
1500057009 qp 49264 (182AFF70-1147-4E30-888E-E1E3D624A056.1)"
Jul 14 14:30:09 vpopmail qmail: 1500057009.947266 starting delivery 531: 
msg 29963 to local barontel.com-postmaster@barontel.com
Jul 14 14:30:09 vpopmail qmail: 1500057009.947401 status: local 1/10 
remote 0/20
Jul 14 14:30:09 monitor sSMTP[49255]: Sent mail for munin@monitor (221 
mxbt1.barontel.com closing connection. Have a jolly good day.) uid=842 
username=root outbytes=668
Jul 14 14:30:09 haraka haraka[97119]: [NOTICE] 
[182AFF70-1147-4E30-888E-E1E3D624A056.1] [core] disconnect 
ip=172.16.15.11 rdns="monitor" helo="monitor" relay=N early=N esmtp=N 
tls=N pipe=N errors=0 txns=1 rcpts=1/0/0 msgs=1/0/0 bytes=580 lr="" 
time=9.695
Jul 14 14:30:09 spamassassin spamd[29917]: prefork: child states: IIIII
Jul 14 14:30:10 vpopmail qmail: 1500057010.051877 delivery 531: success: 
did_0+0+1/
Jul 14 14:30:10 vpopmail qmail: 1500057010.052268 status: local 0/10 
remote 0/20
Jul 14 14:30:10 vpopmail qmail: 1500057010.052523 end msg 29963

**Comment by s571** [comment]
In access.domains have:
monitor

Have it like that because its munin@monitor

Yet the mail for munin@monitor comes in anyway:
Jul 14 14:35:08 haraka haraka[97119]: [NOTICE] 
[4AC0B519-16E6-4271-BA22-2F45747D2A73.1] [core] sender <munin@monitor> 
code=CONT msg=""
Jul 14 14:35:08 haraka haraka[97119]: [NOTICE] 
[4AC0B519-16E6-4271-BA22-2F45747D2A73.1] [core] recipient 
<postmaster@barontel.com> code=OK msg="" sender="munin@monitor"
Jul 14 14:35:09 spamassassin spamd[41889]: spamd: connection from haraka 
[172.16.15.9]:64060 to port 783, fd 5
Jul 14 14:35:09 spamassassin spamd[41889]: spamd: checking message 
(unknown) for postmaster@barontel.com:58
Jul 14 14:35:09 spamassassin spamd[41889]: spamd: clean message 
(0.4/5.0) for postmaster@barontel.com:58 in 0.6 seconds, 872 bytes.
Jul 14 14:35:09 spamassassin spamd[41889]: spamd: result: . 0 - 
ALL_TRUSTED,MISSING_MID,TO_MALFORMED 
scantime=0.6,size=872,user=postmaster@barontel.com,uid=58,required_score=5.0,rhost=haraka,raddr=172.16.15.9,rport=64060,mid=(unknown),autolearn=no 
autolearn_force=no
Jul 14 14:35:09 haraka haraka[97119]: [NOTICE] 
[4AC0B519-16E6-4271-BA22-2F45747D2A73.1] [core] message mid="" size=580 
rcpts=1/0/0 delay=0.652 code=CONT msg=""
Jul 14 14:35:09 vpopmail qmail: 1500057309.957381 new msg 29971
Jul 14 14:35:09 vpopmail qmail: 1500057309.957770 info msg 29971: bytes 
1317 from <munin@monitor> qp 49457 uid 89
Jul 14 14:35:09 haraka haraka[97119]: [NOTICE] 
[4AC0B519-16E6-4271-BA22-2F45747D2A73.1] [core] queue code=OK msg="ok 
1500057309 qp 49457 (4AC0B519-16E6-4271-BA22-2F45747D2A73.1)"
Jul 14 14:35:09 monitor sSMTP[49452]: Sent mail for munin@monitor (221 
mxbt1.barontel.com closing connection. Have a jolly good day.) uid=842 
username=root outbytes=668
Jul 14 14:35:09 haraka haraka[97119]: [NOTICE] 
[4AC0B519-16E6-4271-BA22-2F45747D2A73.1] [core] disconnect 
ip=172.16.15.11 rdns="monitor" helo="monitor" relay=N early=N esmtp=N 
tls=N pipe=N errors=0 txns=1 rcpts=1/0/0 msgs=1/0/0 bytes=580 lr="" 
time=9.714
Jul 14 14:35:09 vpopmail qmail: 1500057309.961246 starting delivery 533: 
msg 29971 to local barontel.com-postmaster@barontel.com
Jul 14 14:35:09 vpopmail qmail: 1500057309.961341 status: local 1/10 
remote 0/20
Jul 14 14:35:10 spamassassin spamd[29917]: prefork: child states: IIIII
Jul 14 14:35:10 vpopmail qmail: 1500057310.052093 delivery 533: success: 
did_0+0+1/
Jul 14 14:35:10 vpopmail qmail: 1500057310.052376 status: local 0/10 
remote 0/20
Jul 14 14:35:10 vpopmail qmail: 1500057310.052484 end msg 29971

**Comment by s571** [comment]
Let me make sure I understand what you wrote below.
iiuc you use access.domains file to block aol.com and use it to 
whitelist !friend@aol.com

If that is correct, you are not using mail_from.access files?
Thanks.
