### ISSUE TITLE
error during provision Haraka

### ISSUE THREAD

**Issue by tmechlinski** [msimerson/Mail-Toaster-6#242]
### Expected behavior
Schould be installd.
### Observed behavior
A lot of Warrnings newer stops.

 dir "/usr/local/lib/node_modules/Haraka/node_modules/iconv/.node-gyp/8.1.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/Haraka/node_modules/iconv/.node-gyp"
gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/local/lib/node_modules/Haraka/node_modules/iconv/.node-gyp/8.1.4"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/Haraka/node_modules/iconv/.node-gyp"

### Steps to reproduce
Fresh installation of Mail-Toaster-6 during provision Haraka.

**Comment by msimerson** [comment]
Known issue. It'll resolve itself when node 8 is available from `pkg install node`. In the meantime, a workaround is to install node 6 instead: `pkg install node6 npm3`. The easiest way to do that is edit `provision-haraka.sh` and then run `sh provision-haraka.sh`.

**Comment by Infern1** [comment]
Even with Node 8.3.0 this problem exists

``
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/local/bin/node',
gyp verb cli   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.3.0 | freebsd | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/local/bin/python2
gyp verb check python version `/usr/local/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.13\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.3.0
gyp verb command install [ '8.3.0' ]
gyp verb install input version string "8.3.0"
gyp verb install installing version: 8.3.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.3.0
gyp verb ensuring nodedir is created /root/.node-gyp/8.3.0
gyp WARN EACCES user "robl" does not have permission to access the dev dir "/root/.node-gyp/8.3.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/Haraka/node_modules/modern-syslog/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
``

**Comment by msimerson** [comment]
Was that 8.3 installed from pkg or port?  When I tested installing node 8 from ports a couple weeks ago it worked fine.

**Comment by Infern1** [comment]
Pkg

**Comment by msimerson** [comment]
I wonder if installing it from ports works. If so, that's a workaround. Also, if so, what does the port install (build tools?) that the pkg does not? That might be the source of the issue.

**Comment by Infern1** [comment]
I could install it with node8 from pkg, however I used the --unsafe-perm then this error is not there.

Will try if the port version does any different

**Comment by msimerson** [comment]
I've investigated this further today. The problem isn't node 8, it's npm v5 (and maybe v4). In any case, installing node 6/npm 3, as the current port does, is a workaround until the brain damaged-ness in NPM gets fixed.

* npm/npm#18069
* npm/npm#17736
