### ISSUE TITLE
Duplicate lines in .qmail from vacation

### ISSUE THREAD

**Issue by s571** [msimerson/Mail-Toaster-6#244]
After one disables their vacation in qmail admin, .qmail still has:

> |preline /usr/local/bin/maildrop /etc/mailfilter
> | /usr/local/bin/maildrop /usr/local/etc/mail/mailfilter

Is there a fix for this?
Thanks

**Comment by msimerson** [comment]
This is a common problem on upgrades. The "fix" is to make sure the contents of .qmail files matches the value that's compiled into qmailadmin.

**Comment by s571** [comment]
The line in all .qmail for users was:

`|preline /usr/local/bin/maildrop /etc/mailfilter`

The above line is from prior MT systems. So it seems the correct line that must be placed in .qmail files is

`| /usr/local/bin/maildrop /usr/local/etc/mail/mailfilter`

**Comment by msimerson** [comment]
Thanks for following up. That might help others.
