### ISSUE TITLE
Provision Haraka hangs

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#250]
### Expected behavior
haraka gets provisioned

### Observed behavior
hangs here for more than 10minutes

`
jexec stage npm install -g Haraka ws express
[               ...] / finalize:haraka-plugin-watch: sill finalize /usr/local/lib/node_modules/Haraka/node_modules/haraka-plugin-watch
[               ...] / finalize:haraka-plugin-watch: sill finalize /usr/local/lib/node_modules/Haraka/node_modules/haraka-plugin-watch
`

See log here: 
https://gist.github.com/Infern1/049191c369b5f055b0ba2c2ef582f3f8

### Steps to reproduce

provision haraka

**Comment by msimerson** [comment]
Duplicate of #242 . There's a fix posted there and also included in #248

**Comment by Infern1** [comment]
Don't think it's duplicate, since node6 is installed

**Comment by msimerson** [comment]
Oh, you caught me getting my daily exercise, jumping to conclusions. Doh!

**Comment by msimerson** [comment]
Is this on a new/fresh VM, or re-installing?  (On a Fresh 11.1 install, it's working fine here). If it's a re-install, there's a few things...

**Comment by Infern1** [comment]
> Is this on a new/fresh VM, or re-installing? (On a Fresh 11.1 install, it's working fine here). If it's a re-install, there's a few things...

This is still 10.3p21 (yes need to upgrade but don't made the time for it, still have some customized provisioned jails and don't know if they will work when upgrading to 11.1 and don't update the jail itself)

So I wanted to upgrade to the latest haraka so that is why I went on provisioning a new haraka jail, also seeing the changes you made, was curious of they work

**Comment by msimerson** [comment]
Ah, two differences then. Have you updated pkg to install from the latest branch?  If not, add this in your base jail, recreate the `10.3p21` snapshot, and then try again:

````
mkdir -p /usr/local/etc/pkg/repos
echo 'FreeBSD: {  url: "pkg+http://pkg.FreeBSD.org/${ABI}/latest" }' \
    > /usr/local/etc/pkg/repos/FreeBSD.conf
````

**Comment by Infern1** [comment]
> Ah, two differences then. Have you updated pkg to install from the latest branch? If not, add this in your base jail, recreate the 10.3p21 snapshot, and then try again:

I did a reprovision of the base (since I did see the changes for getting the latest pkg). However this line is not in.
Will try again

**Comment by msimerson** [comment]
I'm running 10.3p21 on one server as well, so I'm about to see if I can't recreate this issue there.

**Comment by msimerson** [comment]
I can't reproduce this on my 10.3p21 system. I reprovisioned host, then base, then haraka, and it worked as expected.

**Comment by msimerson** [comment]
````
# /bin/freebsd-version 
10.3-RELEASE-p21
# jexec stage /bin/freebsd-version 
10.3-RELEASE-p21
# jexec stage node --version
v6.11.2
# jexec stage npm --version
3.10.10
````

**Comment by Infern1** [comment]
updated from git
removed snapshots of stage and base
and works....
