### ISSUE TITLE
index page should only include installed options

### ISSUE THREAD

**Issue by msimerson** [msimerson/Mail-Toaster-6#261]
### Expected behavior

When visiting the toaster index page in a browser, the only options in the menus should be options that are installed.

### Observed behavior

Options such as non-installed webmail and monitoring are listed.

### ToDo

Dynamically add webmail, monitoring, and admin items to the index page when they are installed.

**Comment by msimerson** [comment]
TODO
- [ ] if TOASTER_NRPE is not set, remove it from index page
- [ ] if TOASTER_MUNIN is not set, remove it from index page
- if jail is not installed, remove from the index page:
    - [ ] sqwebmail
    - [ ] squirrelmail
    - [ ] rainloop
    - [ ] roundcube
    - [ ] rspamd

**Comment by msimerson** [comment]
When those jails are installed, add themselves to the index page? Maybe enable/disable instead of removal.

**Comment by Infern1** [comment]
LGTM not using the index page, so cannot comment. But fix makes sense

**Comment by msimerson** [comment]
Perhaps a better solution is do a quick HTTP test (in JS) and only enable **functioning** components.
