### ISSUE TITLE
idea: mysql defaults to off

### ISSUE THREAD

**Issue by msimerson** [msimerson/Mail-Toaster-6#262]
I'm considering setting mysql to disabled in the default config for a few reasons:

1. it's a heavyweight daemon
2. for email purposes, it's only required for large installs ( > 500 users)
3. it's easy to enable
4. if vchkpw files are outgrown, they can be converted to mysql

```diff
diff --git a/mail-toaster.sh b/mail-toaster.sh
index 76bacb9..bba827b 100755
--- a/mail-toaster.sh
+++ b/mail-toaster.sh
@@ -43,7 +43,7 @@ export JAIL_NET6="$(get_random_ip6net)"
 export ZFS_VOL="zroot"
 export ZFS_JAIL_MNT="/jails"
 export ZFS_DATA_MNT="/data"
-export TOASTER_MYSQL="1"
+export TOASTER_MYSQL="0"
 export TOASTER_MARIADB="0"
 export TOASTER_PKG_AUDIT="0"
 export SQUIRREL_SQL="1"
@@ -84,9 +84,9 @@ export ZFS_DATA_MNT=${ZFS_DATA_MNT:="/data"}
 export FBSD_MIRROR=${FBSD_MIRROR:="ftp://ftp.freebsd.org"}
 
 # See https://github.com/msimerson/Mail-Toaster-6/wiki/MySQL
-export TOASTER_MYSQL=${TOASTER_MYSQL:="1"}
+export TOASTER_MYSQL=${TOASTER_MYSQL:="0"}
 export TOASTER_MARIADB=${TOASTER_MARIADB:="0"}
-export SQUIRREL_SQL=${SQUIRREL_SQL:="1"}
+export SQUIRREL_SQL=${SQUIRREL_SQL:="$TOASTER_MYSQL"}
 export TOASTER_NTP=${TOASTER_NTP:="ntp"}
 
 if [ "$TOASTER_MYSQL" = "1" ]; then
````

**Comment by Infern1** [comment]
I understand your arguments and for the mail system MySQL is probably not needed. So agree to change the default.

However care has to be taken for all jails depending on it:

- [ ] - roundcube
- [ ] - wordpress
- [ ] - horde
- [ ] - mediawiki
etc

So if people decide to install these jails it would be nice if there will be a check if mysql jail exisiting. If not stop the script

**Comment by msimerson** [comment]
> So if people decide to install these jails it would be nice if there will be a check if mysql jail exisiting. If not stop the script

Excellent point.
