### ISSUE TITLE
replace maildrop with sieve

### ISSUE THREAD

**Issue by msimerson** [msimerson/Mail-Toaster-6#263]
#### TODO

* [x] add sieve rule to to drop rspamd tagged spam into .Junk folder
* [x] add sieve rule to to drop spamassassin tagged spam into .Junk folder
* useful [sieve examples](https://support.tigertech.net/sieve)

With the dovecot sieve server now active, users can log in to rainloop, visit their settings and generate sieve rules. I just created one on a test VM and it dropped the file `example.com/postmaster/.dovecot.sieve`, which is a symlink to `sieve/rainloop.user.sieve` which contains:

````

require ["fileinto"];

# This is RainLoop Webmail sieve script.
# Please don't change anything here.
# RAINLOOP:SIEVE

/*
BEGIN:FILTER:cday8eru4ha68uwvxgb4dppwfwv7cmlw
BEGIN:HEADER
eyJJRCI6ImNkYXk4ZXJ1NGhhNjh1d3Z4Z2I0ZHBwd2Z3djdjbWx3IiwiRW5hYmxlZCI6dHJ1ZS
wiTmFtZSI6InRyYXNoIGNyb24iLCJDb25kaXRpb25zIjpbeyJGaWVsZCI6IkZyb20iLCJUeXBl
IjoiQ29udGFpbnMiLCJWYWx1ZSI6Im11bmluIiwiVmFsdWVTZWNvbmQiOiIifV0sIkNvbmRpdG
lvbnNUeXBlIjoiQW55IiwiQWN0aW9uVHlwZSI6Ik1vdmVUbyIsIkFjdGlvblZhbHVlIjoiVHJh
c2giLCJBY3Rpb25WYWx1ZVNlY29uZCI6IiIsIkFjdGlvblZhbHVlVGhpcmQiOiIiLCJBY3Rpb2
5WYWx1ZUZvdXJ0aCI6IiIsIktlZXAiOnRydWUsIlN0b3AiOnRydWUsIk1hcmtBc1JlYWQiOmZh
bHNlfQ==
END:HEADER
*/

if header :contains ["From"] "munin"
{
    fileinto "Trash";
    stop;
}

/* END:FILTER */
````

For those sieve rules to work during delivery, we need to start delivering mail to mailboxes to dovecot LMTP (instead of smtp forward to qmail). 

That would mean mailfilter stops working. Which also means we should first migrate mailfilter rules to a site-side sieve config.

**Comment by Infern1** [comment]
Yes sieve is more robust for future implementations. 
Horde (ingo) can output also sieve rules so this is easy to migrate personal maildrop files
Roundcube has no active sieve plugin (isn't maintained)
Seems some MUA have Sieve support

**Comment by msimerson** [comment]
> Roundcube has no active sieve plugin (isn't maintained)

I happened past the roundcube [1.3.0](https://github.com/roundcube/roundcubemail/releases/tag/1.3.0) and [1.3.1](https://github.com/roundcube/roundcubemail/releases/tag/1.3.1) changelogs and noticed that BOTH had a number of updates for managesieve. Apparently it is being maintained.

**Comment by msimerson** [comment]
Update: this now mostly happens. Because messages destined to qmail mailboxes is delivered by dovecot LMTP, sieve rules are automatically processed. I use rainloop's filter settings to manage the sieve rules.

**Comment by msimerson** [comment]
Closing as "mostly done." Nothing smart automatically happens like the importing of legacy maildrop filters, but I doubt I'll ever implement such a thing.
