### ISSUE TITLE
Provision dovecot

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#271]
### Expected behavior
stops during compile sieve

see: https://gist.github.com/Infern1/b4bb8ee17d848346e4d88114f0885538

### Observed behavior

sh provision-dovecot.sh

**Comment by msimerson** [comment]
Well that stinks. Apparently dovecot and dovecot-pigeonhole are out of sync in the ports tree. I wonder how often that happens?

**Comment by Infern1** [comment]
I have no clue, seems they are updated regularly, so quite strange

**Comment by msimerson** [comment]
This is working for me today, so it appears to have resolved itself. Reopen if necessary.
