### ISSUE TITLE
access files not working??

### ISSUE THREAD

**Issue by s571** [msimerson/Mail-Toaster-6#272]
### Expected behavior
block domains added to **access.domains** and/or **mail_from.access.blacklist**

### Observed behavior
in **access domains**, have added:
match.com

In **mail_from.access.blacklist** have added:
matchmail@connect.match.com
mailer@connect.match.com

haraka is not blocking match.com
Received: from mx3.connect.match.com (mx3.connect.match.com [208.83.240.159])
From: "Match by Mail" <matchmail@connect.match.com>

What are we doing wrong to prevent anything from match.com from getting in?
Thanks.

**Comment by msimerson** [comment]
Look at the karma scores being assigned to hosts lists and adjust as required.

**Comment by s571** [comment]
I presume you mean /data/haraka/config/karma.ini 

If so ours has very little in it


[redis]
dbid=1
server_ip=172.16.15.16

[deny_excludes]
plugins=send_email, access, helo.checks, data.headers, mail_from.is_resolvable, avg, limit, attachment, tls

There is another karma.ini located at /data/haraka/node_modules/haraka-plugin-log-reader/config/karma.ini

Question is, should /data/haraka/node_modules/haraka-plugin-log-reader/config/karma.ini be copied to /data/haraka/config/karma.ini and then change values?

**Comment by msimerson** [comment]
yes.

**Comment by s571** [comment]
yes to what.. you are fast!

**Comment by s571** [comment]
cp original ?

**Comment by s571** [comment]
running service jail stop, service jail start to make sure it reads new karma.ini

**Comment by s571** [comment]
Would the following two entries in the karma.ini now working be right:

100 = access    | whitelist     | equals | true |  9  | Policy Whitelist
101 = access    | blacklist     | equals | true | -15  | Policy Blacklist | Unsubscribe the user, stop spamming them.

**Comment by s571** [comment]
Something appears to not be working because the mail from match.com still gets in. If there is a misconfiguration, where is it?

Received: (qmail 16813 invoked by uid 89); 1 Oct 2017 09:05:53 -0000
Received: from unknown (HELO redacted.com) (172.16.15.9)
  by vpopmail with SMTP; 1 Oct 2017 09:05:53 -0000
Authentication-Results: redacted.com; iprev=pass; spf=pass smtp.mailfrom=connect.match.com
Received-SPF: Pass (redacted.com: domain of connect.match.com designates 208.83.240.160 as permitted sender) receiver=redacted.com; identity=mailfrom; client-ip=208.83.240.160; helo=mx4.connect.match.com; envelope-from=<bounces-MA-1-157-9f830e41-36d1-4b22-88a6-488d18ef8732@connect.match.com>
Received-SPF: Pass (redacted.com: domain of mx4.connect.match.com designates 208.83.240.160 as permitted sender) receiver=redacted.com; identity=helo; client-ip=208.83.240.160; helo=mx4.connect.match.com; envelope-from=<bounces-MA-1-157-9f830e41-36d1-4b22-88a6-488d18ef8732@connect.match.com>
**Received: from mx4.connect.match.com (mx4.connect.match.com [208.83.240.160])**
        by redacted.com (Haraka/2.8.13) with ESMTP id C55FF1E0-1C64-4975-8072-9F2E389D1E15.1
        envelope-from <bounces-MA-1-157-9f830e41-36d1-4b22-88a6-488d18ef8732@connect.match.com>;
        Sun, 01 Oct 2017 05:05:45 -0400

**karma.ini** has the following two changes:

100 = access    | whitelist     | equals | true |  12  | Policy Whitelist
101 = access    | blacklist     | equals | true | **-15**  | Policy Blacklist | Unsubscribe the user, stop spamming them.

 **mail_from.access.blacklist** has :
matchmail@connect.match.com
mailer@connect.match.com

**access.domains** has :
match.com

**Comment by s571** [comment]
Trying to rebuild. Rebuilt haraka following your outlined steps. When new haraka jail starts, haraka not running. 

Trying to provision everything in order of your jails page.
When doing so, runs out of swap space. Memory is 4096MB, Swap is 2048MB. Updating VM to have 8192MB memory and will continue on reboot.

Even doubling memory, swap size remains same:
Swap: 2048M Total, 2048M Free

**provision dovecot fails**

pipe :copy "learn-ham-rspamd.sh" [ "${username}" ];
jexec stage /usr/local/bin/sievec -c /data/etc/dovecot.conf /usr/local/lib/dovecot/sieve/report-ham.sieve
report-ham: line 1: error: require command: unknown Sieve capability `vnd.dovecot.pipe'.
report-ham: line 1: error: require command: unknown Sieve capability `imapsieve'.
report-ham: line 15: error: unknown command 'pipe' (only reported once at first occurrence).
report-ham: error: validation failed.
sievec(root): Fatal: failed to compile sieve script '/usr/local/lib/dovecot/sieve/report-ham.sieve'
#

try again...

provision dovecot fails again same place as above.
