### ISSUE TITLE
Haraka doesn't start after provision haraka

### ISSUE THREAD

**Issue by s571** [msimerson/Mail-Toaster-6#276]
### Expected behavior
haraka to be running
### Observed behavior
**haraka not running**
 # jexec haraka
# ps auxw |grep haraka
root 2270  0.0  0.0  14796   1572  0  R+J  08:32   0:00.00 grep haraka
root@haraka:/ #

# /usr/local/etc/rc.d/haraka start
loaded TLD files: 1=1544 2=6156 3=2246
loaded 8357 Public Suffixes

root@haraka:/ # ps auxw |grep haraka
root 2334  0.0  0.0  14796   1612  0  R+J  08:33   0:00.00 grep haraka
root@haraka:/ #

**Comment by s571** [comment]
Created new VM. Installed FreeBSD 11 exactly as your page says.  Everything installed (up to Haraka). When haraka was start after: 

jail_list: dns mysql redis clamav dcc rspamd vpopmail dovecot geoip -> dns mysql redis clamav dcc rspamd vpopmail dovecot geoip haraka

Success! A new 'haraka' jail is provisioned

haraka doesn;t show in maillog. top show 97% swap use. Memory installed 4096MB, swap size is 2048MB, cpu count=4

rebooting....

~ # ps auxw |grep haraka
root    2595   0.0  0.1   14796   2316  0  S+   09:57   0:00.00 grep haraka
~ #

~ # jexec haraka
root@haraka:/ # /usr/local/etc/rc.d/haraka start
loaded TLD files: 1=1544 2=6156 3=2246
loaded 8357 Public Suffixes
root@haraka:/ # /usr/local/etc/rc.d/haraka start
loaded TLD files: 1=1544 2=6156 3=2246
loaded 8357 Public Suffixes
root@haraka:/ # /usr/local/etc/rc.d/haraka start
loaded TLD files: 1=1544 2=6156 3=2246
loaded 8357 Public Suffixes

**Comment by msimerson** [comment]
Don't know. I just provisioned anew on a FreeBSD 11 VM and it worked for me.
