### ISSUE TITLE
haraka must be running but not delivering mail

### ISSUE THREAD

**Issue by s571** [msimerson/Mail-Toaster-6#278]
Other old issue is too long. Continue here

On the MT6 server can telnet to haraka

# telnet 172.16.15.9 25
Trying 172.16.15.9...
Connected to haraka.
Escape character is '^]'.
220 host.redacted-domain.com ESMTP Haraka 2.8.16 ready

So we know it';s alive. But haraka doesn't appear in /var/log/maillog at all.

**Comment by s571** [comment]
new MT6.

~ # ls /data
ls: /data: No such file or directory

# freebsd-update fetch
# freebsd-update install

FreeBSD 11.0-RELEASE-p12 (GENERIC) #0: Wed Aug  9 10:03:39 UTC 2017

fetch https://raw.githubusercontent.com/msimerson/Mail-Toaster-6/master/mail-toaster.sh
Certificate verification failed for /C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 High Assurance Server CA
34374329736:error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:/usr/src/secure/lib/libssl/../../../crypto/openssl/ssl/s3_clnt.c:1264:
fetch: https://raw.githubusercontent.com/msimerson/Mail-Toaster-6/master/mail-toaster.sh: Authentication error

I guess you have found something and are fixing it.

**Comment by s571** [comment]
New MT6..
/etc/resolv.conf doesn't have nameserver 172.16.15.3 after install
I've added it. 
But now dovecot is failing ..
I will wait until all /data/vpopmail is rsync'd to new MT6. Probably the reason.

**Comment by s571** [comment]
Trying to rsync old /data/vpopmail new MT6 /data/vpopmail
Keep getting out of swapspace errors
Memory was 3072MB 2vCPUs

Just changed it to 4096MB, 4vCPUs
What might the culprit?

**Comment by s571** [comment]
![swap-space](https://user-images.githubusercontent.com/29606862/31087553-73763558-a76b-11e7-8dd2-8c7270b1afe3.png)
every few minutes. Locks up server have to reboot. Real PAIN

**Comment by msimerson** [comment]
Sheesh, use your system tools to see what's using all the RAM.

**Comment by s571** [comment]
/data/vpopmail has been rsync'd to new MT6. Still cannot get any mail. See errors in maillog like"

dovecot dovecot: auth-worker: Error: Error. Domain domain-redactedcom was not found in the assign file

Haraka doesn't show up at all in maillog.

 # telnet haraka 25
Trying 172.16.15.9...
Connected to haraka.
Escape character is '^]'.
220 null ESMTP Haraka 2.8.16 ready


Oct  2 13:26:17 dovecot dovecot: auth: Fatal: vpopmail: vauth_open() failed
Oct  2 13:26:17 dovecot dovecot: master: Error: service(auth): command startup failed, throttling for 16 secs
Oct  2 13:26:17 dovecot dovecot: imap-login: Disconnected: Auth process broken (disconnected before auth was ready, waited 7 secs): user=<>, rip=99.237.72.210, lip=172.16.15.15, TLS, session=<xTsbrJNaQeRj7UjS>

**Comment by s571** [comment]
mxbt1 sm-mta[678]: STARTTLS=server: file /etc/mail/certs/dh.param unsafe: No such file or directory

is this supposed to be this way?
