### ISSUE TITLE
Add dovecot stats

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#288]
### Idea

would it be good if we add Dovecot statistics
See here: https://wiki2.dovecot.org/Statistics

If this would be good, will make a pull for this

**Comment by Infern1** [comment]
Found a nice [munin plugin](https://github.com/munin-monitoring/contrib/blob/master/plugins/dovecot/dovecot_stats_)
Since I still quite like to look at munin for a quick status this is what I use

So an option to mail-toaster.conf
```
TOASTER_DOVECOTSTATS="1" 
```

Then some docs in monitor will do?

BTW after my holiday ;)

**Comment by Infern1** [comment]
For now this also works [dovecot plugin](https://github.com/munin-monitoring/contrib/blob/master/plugins/dovecot/dovecot1)

![image](https://user-images.githubusercontent.com/928787/31685863-c7b2f8b6-b384-11e7-895d-938f94a9451a.png)

**Comment by msimerson** [comment]
> So an option to mail-toaster.conf

I was thinking something like TOASTER_MUNIN instead. Such that each provision script can have (optional) munin-node installed with their custom plugins.

**Comment by msimerson** [comment]
I'm tempted to close this PR. As of version 2.3, Dovecot has deprecated the stats (see the Statistics page) I had working with telegraf/grafana and likely for this munin plugin too. You can enable them as old-stats to keep existing integrations working. New stuff will want to use the newer format which nothing else supports yet. For the foreseeable future, dovecot stats are likely to require the sysadmin to do some fiddling to get/keep working reliably.

**Comment by Infern1** [comment]
If it’s removed from dovecot. IMHO this can be closed

**Comment by msimerson** [comment]
Moved to [ROADMAP](https://github.com/msimerson/Mail-Toaster-6/wiki/ROADMAP)
