### ISSUE TITLE
do we need rspamd phising

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#302]
### Observed behavior
rspamd using 600 MB ram for each process

Is know behaviour:
https://github.com/vstakhov/rspamd/issues/1686

If you have a virtual server, the only thing limited is RAM, by having rspamd taking almost 2GB, not much is left.

### Steps to reproduce
Enable phising

**Comment by msimerson** [comment]
needed? Of course not.

Should it should be enabled by default?  Maybe not? It's at least mildly duplicating clamd functionality.
