### ISSUE TITLE
Haraka jail no log rotation

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#303]
### Expected behavior
log rotation in haraka jail

### Observed behavior
haraka logs to /var/log/maillog and we do set up newsyslog, however the crontab for newsyslog is disabled, so no logs rotated.

Resulting in large maillog

I think we should remove the commented out newsyslog in /etc/crontab (done in the base jail)

**Comment by msimerson** [comment]
Doh! I thought I had fixed that, but apparently not yet in repo.

I agree it's a bug and your proposed solution is correct.

**Comment by msimerson** [comment]
fixed in #309

**Comment by msimerson** [comment]
Found it. I had half-enabled log rotation in #273.
