### ISSUE TITLE
provision geoip error -> npm and Node.js incompatability

### ISSUE THREAD

**Issue by hammer185** [msimerson/Mail-Toaster-6#306]
###Observed behavior
jexec stage npm install -g maxmind-geolite-mirror
WARNING: You are likely using a version of node-tar or npm that is incompatible with this version of Node.js.
Please use either the version of npm that is bundled with Node.js, or a version of npm (> 5.5.1 or < 5.4.0) or node-tar (> 4.0.1) that is compatible with Node.js 9 and above.
/usr/local/bin/node[17868]: ../src/node_zlib.cc:437:static void node::(anonymous namespace)::ZCtx::Init(const FunctionCallbackInfo<v8::Value> &): Assertion `args.Length() == 7 && "init(windowBits, level, memLevel, strategy, writeResult, writeCallback," " dictionary)"' failed.
 1: node::Abort(void) [/usr/local/bin/node]
 2: node::Assert(char const* const[4]*) [/usr/local/bin/node]
 3: _ZNSt3__16vectorIPN4node14SigintWatchdogENS_9allocatorIS3_EEE21__push_back_slow_pathIRKS3_EEvOT_ [/usr/local/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(void(*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/usr/local/bin/node]
 5: v8::internal::Isolate*<v8::internal::Object> v8::internal::Builtins::InvokeApiFunction(v8::internal::Isolate*, bool, v8::internal::Handle<v8::internal::HeapObject>(int, v8::internal::Object*, v8::internal::HeapObject) [/usr/local/bin/node]
 6: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
Abort trap (core dumped)

**Comment by msimerson** [comment]
Node 9 is apparently the default version of node now. I think it should still be node 8 and node 9 should be node-devel, but oh well. For now, edit the provision-geoip.sh script and have it install the node8 port instead. Then run the script with ./prov....

**Comment by hammer185** [comment]
I used both npm-node8 and npm-node6 in testing, both did not show errors.  Also, just an FYI, I had to add stage_pkg_install python || exit in provision-haraka.sh also it was needed and without it provision-haraka.sh failed.  Hopefully you'll get a new mail-toaster.sh to address these issues soon also.

**Comment by hammer185** [comment]
Oops, not a new mail-toaster.sh, now I see it's doing a fetch.  Maybe updates on your end where you store the provision files.

**Comment by msimerson** [comment]
Those files are stored here in this repository.
