### ISSUE TITLE
haraka provision error

### ISSUE THREAD

**Issue by tmechlinski** [msimerson/Mail-Toaster-6#312]
### Expected behavior
Should be provisioned.

### Observed behavior
------------------------------------------------------------------------
jexec stage npm install --production -g haraka/Haraka ws express
/usr/local/bin/spf -> /usr/local/lib/node_modules/Haraka/bin/spf
/usr/local/bin/dkimverify -> /usr/local/lib/node_modules/Haraka/bin/dkimverify
/usr/local/bin/haraka_grep -> /usr/local/lib/node_modules/Haraka/bin/haraka_grep
npm ERR! path /usr/local/lib/node_modules/Haraka/bin/haraka
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/Haraka/bin/haraka'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-12-16T09_52_25_079Z-debug.log

### Steps to reproduce
Fresh installation
run: provision haraka

###
FreeBSD 11.1-RELEASE-p4 FreeBSD 11.1-RELEASE-p4 #0: Tue Nov 14 06:12:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by msimerson** [comment]
I have an update that addresses this now.
