### ISSUE TITLE
Haraka express not working

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#318]
### Expected behavior
working watch

### Observed behavior
 ```
[ERROR] [-] [core] express failed to load. No http server.  Try installing express with: npm install -g express
```

```
# npm  list -g --depth=0
/usr/local/lib
+-- express@4.16.2
+-- Haraka@2.8.16 -> /tmp/Haraka
+-- node-gyp@3.6.2
`-- npm@5.6.0
```
### Steps to reproduce
Provision Haraka

**Comment by msimerson** [comment]
Is this an upgrade, new, or reprovisioned jail?

I saw this issue and thought I had solved it by installing express in /data/node_modules, with the rest of the MT6 installed NPM packaged haraka plugins.

**Comment by Infern1** [comment]
Just a reprovision of the haraka jail

**Comment by Infern1** [comment]
Fixed by running manual

```
cd /data && npm install --only=prod  ws express
```
