### ISSUE TITLE
make.conf not correctly configured => dovecot not working

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#324]
### Expected behavior
Working dovecot after reprovision jail dovecot

### Observed behavior
no such user when authenticated with dovecot

### Steps to reproduce
Found that my make.conf in /jails/vpopmail/etc/make.conf was missing these two lines:

```
mail_vpopmail_SET= MYSQL VALIAS
mail_vpopmail_UNSET= CDB
```
And it won't add them since the file is copied from the vpopmail jail, so removed the make.conf from the vpopmail jail and then run the provision-dovecot again and all started working again

**Comment by msimerson** [comment]
I think I know how that happened. The code that copies it over from the last vpopmail jail matched any mail_ pattern and only copied what you had. You apparently didn't have the vpopmail settings in your make.conf file (upgrade issue) and so they weren't added. I have a fix coming.
