### ISSUE TITLE
Haraka jail maillog rotation

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#346]
### Expected behavior
- log rotated in haraka jail

### Observed behavior
- newsyslog is disabled for haraka however all loggin is send to maillog in haraka jail

```
enable_newsyslog() {
	tell_status "enabling newsyslog"
	stage_sysrc newsyslog_enable=YES
	sed -i .bak \
		-e '/^0.*newsyslog/ s/^#0/0/' \
		"$STAGE_MNT/etc/crontab"
}
```
disables the cron

**Comment by msimerson** [comment]
I think I see the problem. The sed substitution is correct:

`s/^#0/0/'` is a substitution that **enables** newsyslog by removing the `#` character.

Newsyslog is disabled by default in new jails:

````
$ grep newsyslog /jails/base/etc/crontab
#0	*	*	*	*	root	newsyslog
````

But the match that precedes the sed substitution is anchored. Remove the `^` anchoring character and it'll work, or add the `#` after the anchor and it'll work.
