### ISSUE TITLE
freegeoip API deprecated, causing error message during provision host

### ISSUE THREAD

**Issue by sn3ak** [msimerson/Mail-Toaster-6#364]
https://github.com/msimerson/Mail-Toaster-6/blob/b5e81d95f8701d14a02656beb0b1e41b7ec0ad93/provision-host.sh#L199 fails due to a changed API.

See [https://github.com/apilayer/freegeoip#readme](https://github.com/apilayer/freegeoip#readme)

**Comment by msimerson** [comment]
If you get a chance, please test #365. Else it'll wait until I get around to testing it.
