### ISSUE TITLE
instructions / process to rebuild base. zfs snapshot exists

### ISSUE THREAD

**Issue by sn3ak** [msimerson/Mail-Toaster-6#369]
### Expected behavior
provision base builds a new version with corrected information

### Observed behavior
# provision base
172.16.15.2
provision-base.sh                             100% of   13 kB   48 MBps 00m00s
loading mail-toaster.conf
mysql enabled
toaster host: mail.mydomain.com
email domain: mydomain.com
IPv6 jail network: fd7a:e5cd:1fc1:xxxx:dead:beef:cafe
shell: /bin/csh
safe name: stage
include/shell.sh                              100% of 2869  B   18 MBps 00m00s
zroot/jails/base-11.2-RELEASE@p4 snapshot exists

### Steps to reproduce
On an existing up to date toaster install, do the following:
sudo sh
. mail-toaster.sh && provision base

### Explaination
For some reason on my install, resolv.conf was never updated with the dns jail's ips for nameservers. My hosts configured DNS servers stopped answering queries thus causing DNS to fail on host and all jails.

I happened to be trying to build a new jail and thus the staged jail kept breaking.

I wished to do the following on the host to allow the staged jail to get access:
echo nameserver 172.16.15.3 >> /etc/resolv.conf
echo nameserver fd7a:e5cd:1fc1:xxxx:dead:beef:cafe:0003 >> /etc/resolv.conf
echo nameserver 1.1.1.1 >> /etc/resolv.conf
provision base

I ultimately 'fixed' it by running zfs destroy on the snapshot and running provision base again, but I am not sure this was the right thing to do.

**Comment by msimerson** [comment]
That was the correct thing to do. I've updated [the base docs](https://github.com/msimerson/Mail-Toaster-6/wiki/Base) to reflect that.

**Comment by sn3ak** [comment]
Thank you!
