### ISSUE TITLE
provision vpopmail should show postmaster password / Wiki should include steps on how to retrieve the postmaster password?

### ISSUE THREAD

**Issue by sn3ak** [msimerson/Mail-Toaster-6#371]
### Expected behavior
Somehow a password should be presented to a user who may not be familiar with vpopmail, or the rest of the toaster.

### Observed behavior
Login to QmailAdmin as postmaster @ mydomain.com
Password: uhhhhhh what password?

### Steps to reproduce
provision vpopmail

### Comments
I suppose the user should scroll up and see where the postmaster account was created and I assume the password was returned. It wasn't in my scroll back buffer when I looked, but I also didn't think to look immediately.

Would it make sense to have provision vpopmail spit out the password at the end of it's execution? or does it make sense to add something like the following to the Wiki:
To retrieve your new postmaster password run the following command
`jexec mysql mysql -e "SELECT pw_name, pw_domain, pw_clear_passwd FROM vpopmail.vpopmail"`

You should get something that looks like the following:
```
+------------+------------------------+-----------------+
| pw_name    | pw_domain              | pw_clear_passwd |
+------------+------------------------+-----------------+
| postmaster | yourdomain.com         | yourpassword    |
+------------+------------------------+-----------------+
```

**Comment by msimerson** [comment]
The easier solution is: `jexec vpopmail /usr/local/vpopmail/bin/vuserinfo postmaster@mydomain.com`. I'm not interested in documenting basic vpopmail usage.

**Comment by sn3ak** [comment]
Yeah, I just came back to modify my query realizing that could potentially dump a lot of data. Your method is definitely better.

And fair enough.
