### ISSUE TITLE
Toaster Support

### ISSUE THREAD

**Issue by sn3ak** [msimerson/Mail-Toaster-6#372]
### Community Support
It appears the mail-toaster list no longer exists and the forum hasn't been used since April.
What is the best way to ask questions that aren't bug reports / feature requests? The friend I am helping has a question. I pointed him towards the forum / your email address @tnpi as listed on the v5 repo but it would be nice if you weren't the only one having to support this.

If the forum is the correct place now/still, should a link be added to the readme.md?

**Comment by msimerson** [comment]
The forums are still there, I check in every so often. I think the mailing list still works, but it's awfully quiet since I stopped supporting MT5. This GitHub repo is currently the only forum for MT6. Its not perfect but it works and I don't have to maintain it.

**Comment by sn3ak** [comment]
Okay, the mail list archives / ezmlm aren't working off tnpi. I haven't seen an email on the mailing list in forever, so I just assumed all combined it was shut down. I'll see if he can subscribe tomorrow.

Thanks!
