### ISSUE TITLE
rainloop: permissions are set at the wrong time resulting in rainloop admin not being able to login with default credentials

### ISSUE THREAD

**Issue by sn3ak** [msimerson/Mail-Toaster-6#375]
### Expected behavior
goto https://mydomain/rainloop/?admin login with admin/12345 and complete configuration on a new install.

### Observed behavior
goto https://mydomain/rainloop/?admin login with WRONG credentials. You get instantly told invalid credentials. Repeat process logging in with default user/pass admin/12345. Interface loads spinning circle and just sits there until it times out some time later

```
root@rainloop:/data/_data_ # ls -al
total 10
drwxr-xr-x  3 root  www  3 Nov 28 11:08 _default_
drwxr-xr-x  3 root  www  3 Dec  5 13:11 .
drwxr-xr-x  4 www   www  9 Dec  5 12:52 ..
```
### Steps to reproduce
See above

### Fix
manually chown -R www:www /data/_data_

I reviewed provision-rainloop.sh and see on line 135 you do this step however, on line 138 you call install_default_ini which seems to set root as owner. Recommend moving line 135 after line 138.

Eventually, I need to learn git so I can just submit patches :-)

Could I update the wiki to include the default credentials / a link to the configuration page for rainloop? or like vpopmail do you want to leave that information out?

Thanks Matt!

**Comment by sn3ak** [comment]
I should probably mention, that even though this case was a fresh install, it happened after the recent FreeBSD security patches, so the jail was rebuilt a second time before it's use. That may be where permissions were changed to root?

**Comment by msimerson** [comment]
> Recommend moving line 135 after line 138.

Done.
