### ISSUE TITLE
rainloop customization appears to break rainloop admin except for domains

### ISSUE THREAD

**Issue by sn3ak** [msimerson/Mail-Toaster-6#376]
### Observed behavior
login to rainloop admin on a fresh install, attempt to change admin password, or change Login, Branding, etc and you will get a red x beside the box

### Testing
vi /usr/local/www/rainloop/rainloop/v/1.12.1/include.php

Comment the following:
```
        function __get_custom_data_full_path()
        {
                return '/data/'; // custom data folder path
        }
```

relaunch admin page, you will have to login again. Change the admin password, also notice on the Domains tab, it adds gmail, etc.

diff -ur /data/_data_ /usr/local/www/rainloop/data/_data_ and notice local has several directories and files that /data does not.

I've tried creating the directories and files manually under /data/_data_/ to match local, but it still doesn't work.

**Comment by sn3ak** [comment]
And further testing shows this is incorrect. 
I can 
create /test && chown -R www:www /test 
change /data/ above to /test/
login and everything works fine and is created correctly

I then went to /data && mkdir old && mv * old/ && mv old/etc .
(I'm being lazy here, I actually moved files and dirs seperately)
Refreshed the admin site, which logged me out, logged in, and everything is created and working fine, but without your preinstalled configuration.

**Comment by sn3ak** [comment]
I *think* this is caused by #375 and poor testing by rainloop.
I believe since the permissions were wrong and rainloop couldn't create all its files on the initial attempts to login, but could create the following files:
```
/data/
  index.html
  index.php
  INSTALLED
  SALT.php
  VERSION
  _data_/
```

That it decided it was installed, and no longer had to create all the other directories and files. It then only would create the /data/_data_/_default_/cache directory and populate.

I cleared the afore mentioned files, including the cache directory, but left your default.ini, launched the admin site again, and everything is as it should be.

**Comment by msimerson** [comment]
It should work now. Follow up here and we can re-open this issue of it's not resolved.
