### ISSUE TITLE
Following Wiki jail order, Haraka doesn't enable SpamAssassin support

### ISSUE THREAD

**Issue by sn3ak** [msimerson/Mail-Toaster-6#377]
### Expected behavior
/data/config/spamassassin.ini created and populated

### Observed behavior
spamassassin support isn't turned on in a fresh setup, as the spamassassin jail doesn't exist yet.

### Steps to reproduce
Build a new Toaster, Follow Wiki order, leaving spamassassin as one of the last tasks. look in /data/haraka/config/ and find spamassassin.ini missing

### Recommendation
This seems like a documentation issue. I feel a simple blurb on the Haraka jail Wiki page would resolve this.

If you intend to use SpamAssassin please provision spamassassin first as the provision haraka script looks for it's existence before enabling it's support. If you've failed to see this, either provision haraka again, or create the following file on the host with the contents below:

/data/haraka/config/spamassassin.ini
```
spamd_socket=172.16.15.6:783
old_headers_action=rename
spamd_user=first-recipient
reject_threshold=10
relay_reject_threshold=7
```

**Comment by msimerson** [comment]
[wiki page](https://github.com/msimerson/Mail-Toaster-6/wiki/Haraka) updated.
