### ISSUE TITLE
Wiki Modifications

### ISSUE THREAD

**Issue by sn3ak** [msimerson/Mail-Toaster-6#378]
Do you mind if I modify the Wiki to include things I've learned or would you prefer I open tickets so that you can approve / reword my suggestions?

Especially I'm looking to add the very basics to get a newcomer started / through the process.

Examples:
vpopmail jail:
What build options should I choose when building the vpopmail jail? 
Which I don't know if I have the answer for, but I would suspect looking over the build that I just need to hit enter as you set what you require and unset what you don't want in the script

So I assume the following would be accurate:
While building vpopmail a configuration selection screen will be displayed. The provision script sets the required options and you can just hit enter to continue the build.

haraka jail: 
dkim signing will be setup if the script /data/haraka/conf/dkim/dkim_key_gen.sh exists. Further setup is required which is outside the scope of this project/Wiki.

Rainloop jail:
At the time of this Wiki modification the default Admin login is admin/12345. Further RainLoop support is outside the scope of this project/Wiki. RainLoop's project can be found at [https://www.rainloop.net](https://www.rainloop.net)

**Comment by msimerson** [comment]
> Do you mind if I modify the Wiki 

That's why it's a wiki. :-)

Go ahead and update them pages. It's helpful to have someone who doesn't know those details bring up such points.

**Comment by sn3ak** [comment]
I just wanted to make sure. From one of my previous tickets I had suggested adding a command to the vpopmail page, so that someone could recover their postmaster password for a new install which you disagreed with. I don't want to add a bunch of stuff you don't want.

As always Matt, Thank you for all your hard work. I've been a mail-toaster user for a number of years. I had been leery of the smtpd changes, but I'm glad I've overcome it.

**Comment by sn3ak** [comment]
Correct, I guess I could have worded that better.

Wonderful! I'll work on getting it added. Thanks!

**Comment by msimerson** [comment]
I just added some links on the [haproxy](https://github.com/msimerson/Mail-Toaster-6/wiki/Haproxy) page. Having a standard `More Info` or `Reference` or `Additional` section like that would probably be useful across the wiki pages.

**Comment by sn3ak** [comment]
Looks good. I'll start adding things as I go along. I've got a few toasters to convert for people.
