### ISSUE TITLE
haraka geoip isn't enabled due to config/plugin change upstream?

### ISSUE THREAD

**Issue by sn3ak** [msimerson/Mail-Toaster-6#380]
### Expected behavior
haraka watch to show geo location (and hopefully asn?)

### Observed behavior
watch only reports "geoip" and "asn"

### Steps to reproduce
On a new/current install 

```sh
grep geoip /data/haraka/config/plugins
# geoip
```

It appears the syntax has changed and [provision-haraka.sh line 45](https://github.com/msimerson/Mail-Toaster-6/blob/ab790377bf5e970f02ba8c5fd6a12526b572628e/provision-haraka.sh#L45) needs to be changed to

```sh
sed -i .bak -e '/^# geoip/ s/# //' "$HARAKA_CONF/plugins"
```

This does fix watch's geoip, but sadly doesn't fix asn. More on that as I debug.

P.S. Do you know of a decent git/github primer, so I can submit patches. Though I guess in the short term I could just attach unified diffs

**Comment by msimerson** [comment]
Probably the easiest is to navigate to the file, click the Edit button, and use GitHub's web based editor. Git is a cruel mistress. Wonderful, once you get to know her, and better than every other VCS, which is why it's so popular. But a real wretched beast until then.
