### ISSUE TITLE
Changing Haraka helo

### ISSUE THREAD

**Issue by lunaticds** [msimerson/Mail-Toaster-6#422]
### Expected behavior
Less a problem, more a question - is there a preferred way to change the helo address to the hostname rather than "haraka". I've played around with a couple of options, but I'd rather not break it just at the moment (too close to Christmas to be breaking things). 

### Observed behavior
At the moment, I'm getting occasional bounces to messages sent from the server complaining that the HELO should respond with a FQDN.

**Comment by msimerson** [comment]
Sure: 

````
echo $FQDN > /data/haraka/config/me
````

Make sure to replace $FQDN with your hosts fully qualified domain name. That command assumes default options. Make sure to test afterwards.

**Comment by lunaticds** [comment]
Excellent, thank you!
