### ISSUE TITLE
check mail-toaster.sh version

### ISSUE THREAD

**Issue by msimerson** [msimerson/Mail-Toaster-6#425]
**Is your feature request related to a problem? Please describe.**

When new features and/or build options are added to mail-toaster.sh, they aren't automatically available until after the operator types `mt6-update`. This can cause subsequent build problems because a new setting (like TOASTER_MSA) don't exist in their version.

**Describe the solution you'd like**

When mail-toaster.sh is sourced, check it against the latest version on github. If it's not up-to-date, bark loudly.

**Describe alternatives you've considered**

We already update the provision scripts before every provision action. We might be able to do the same for mail-toaster.sh and if it updated, 're-source' it. However, this has the disadvantage of making it harder to test newer/beta versions that aren't on github yet.

**Comment by Infern1** [comment]
I agree with you solution

**Comment by msimerson** [comment]
>  this has the disadvantage of making it harder to test newer/beta versions that aren't on github yet

I think we can safely update any time the local file is _older_ than the version on GitHub. If we want to run with a local copy, then we just need an up-to-date mail-toaster.sh, or we need to bump the version number.
