### ISSUE TITLE
rspamd dropped the log module

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#432]
**Describe the bug**
rspamd stopped working upgrade to 2.3 

**To Reproduce**
upgrade to 2.3

See changelog 
https://rspamd.com/doc/migration.html#migration-to-rspamd-20

`Log helper worker has been removed (but probably nobody have used it anyway)`

```
Feb  9 08:54:47  kernel: pid 60859 (rspamd-2.3), jid 9, uid 236: exited on signal 6
Feb  9 08:54:49  kernel: pid 60867 (rspamd-2.3), jid 9, uid 236: exited on signal 6
Feb  9 08:54:49  kernel: pid 60871 (rspamd-2.3), jid 9, uid 236: exited on signal 6
Feb  9 08:54:49  kernel: pid 60868 (rspamd-2.3), jid 9, uid 236: exited on signal 6
Feb  9 08:54:49  kernel: pid 60869 (rspamd-2.3), jid 9, uid 236: exited on signal 6
```

removing logging.inc and rspamd was working again

**Comment by msimerson** [comment]
So perhaps have the rspamd jail installer check for and destroy logging.inc when provisioning?

**Comment by msimerson** [comment]
It appears the [logging worker](https://github.com/rspamd/rspamd/issues/3251) is broken upstream when `type = "syslog";` and is getting worked on. This means no syslog for now.
