### ISSUE TITLE
provision mysql fails

### ISSUE THREAD

**Issue by rricker1** [msimerson/Mail-Toaster-6#437]
provision mysql fails with the following error:
<snip>
   ***   testing mysql   ***

jexec stage mysql -u root --connect-expired-password --password="sfq8ljnYOiVc"
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
</snip>

The root password fails to change and the test fails.

**Comment by msimerson** [comment]
New provision, or reprovisioning?

**Comment by rricker1** [comment]
New provision.

**Comment by msimerson** [comment]
Fixed.
