### ISSUE TITLE
[CURIOSITY]: `nuster` to replace `haproxy` due to performance

### ISSUE THREAD

**Issue by zenny** [msimerson/Mail-Toaster-6#446]
Hi @msimerson,

I was reading a benchmark between `nuster` and other proxies (https://github.com/jiangwenyuan/nuster/wiki/Web-cache-server-performance-benchmark:-nuster-vs-nginx-vs-varnish-vs-squid).

Have you ever thought of using `haproxy`-based `nuster` with cache support as a entry point to all services, particularly http-part in `mail-toaster-6`? Just curious.

Cheers, and stay safe,
/z

**Comment by msimerson** [comment]
Nah. The performance is MT6 is abundantly adequate without adding in the complexity involved in caching. Folks that need caching have the experience using them to deploy them and navigate that additional complexity.

**Comment by zenny** [comment]
@msimerson I really loved to hear your comprehensive, yet to-the-point replies. A genius you are! :+1:  :)
