### ISSUE TITLE
rspam issue with 12.1

### ISSUE THREAD

**Issue by TorontoDave** [msimerson/Mail-Toaster-6#451]
### Steps to reproduce
When installing rspamd, get following error, pkg update -f doesnt help
![rspamd](https://user-images.githubusercontent.com/71776942/94030074-67160800-fd8b-11ea-9192-01fee5df6bc4.jpg)

**Comment by msimerson** [comment]
Dave, did you try running `pkg update -f` as the error describes?

**Comment by TorontoDave** [comment]
Yes, didn't help, possibly port broken,  Fbsd 12.1 p10. Going to start fresh as a test, if reproducible David Foster 704-311 Dixon Road, Etobicoke, Ontario, M9R 1S3  Resd. Linda Vista Norte, Detras estación policia Casa 24, Managua, Nicaragua. 12019 (12.154910, -86.304893) Cell 6472747944 Home 416-247-5837 Nicaragua +505 76176344 UK 01302 638035
-------- Original message --------From: Matt Simerson <notifications@github.com> Date: 2020-09-23  1:48 PM  (GMT-05:00) To: msimerson/Mail-Toaster-6 <Mail-Toaster-6@noreply.github.com> Cc: TorontoDave <dave@canadian.net>, Author <author@noreply.github.com> Subject: Re: [msimerson/Mail-Toaster-6] rspam issue with 12.1 (#451) 
Dave, did you try running pkg update -f as the error describes?

**Comment by msimerson** [comment]
That happens sometimes. Usually self-heals in a day or two.

**Comment by msimerson** [comment]
This issue has fixed itself. I just tested successfully.
