### ISSUE TITLE
provison-haproxy.sh

### ISSUE THREAD

**Issue by tmechlinski** [msimerson/Mail-Toaster-6#455]
**bug**
parsing [/data/etc/haproxy.conf:132] : The 'reqirep' directive is not supported anymore since HAProxy 2.1. Use 'http-request replace-header' instead.

**To Reproduce**
run provison-haproxy.sh

haproxy-2.2.4
Name           : haproxy
Version        : 2.2.4
Installed on   : Tue Oct  6 14:06:00 2020 CEST
Origin         : net/haproxy
Architecture   : FreeBSD:12:amd64
Prefix         : /usr/local
Categories     : net www
Licenses       : LGPL21, GPLv2
Maintainer     : demon@FreeBSD.org
WWW            : http://www.haproxy.org
Comment        : Reliable, high performance TCP/HTTP load balancer
Options        :
	DEVICEATLAS    : off
	DOCS           : on
	DPCRE          : off
	EXAMPLES       : on
	LUA            : off
	OPENSSL        : on
	PROMEX         : off
	SPCRE          : on
Annotations    :
	FreeBSD_version: 1201000
	cpe            : cpe:2.3:a:haproxy:haproxy:2.2.4:::::freebsd12:x64
	repo_type      : binary
	repository     : FreeBSD

**Comment by msimerson** [comment]
MT6 recipe has already been updated. You need to update your haproxy config. If you have local customizations, look in the haproxy script and apply the updates. If you don't, just delete the haproxy config and reprovision.
