### ISSUE TITLE
Alternative method to update a jail other then provision it new

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#456]
I do have a couple of provisioned jails which I did customize quite a bit. So the effort to make this all in the script is big.

So what is the procedure to update this jail to the same FreeBSD release as the base system.

Would be great to add some documentation howto do this.

**Comment by msimerson** [comment]
What's wrong with freebsd-update?

There's even a mostly automated process called `jailmanage update $jailname`

**Comment by Infern1** [comment]
> What's wrong with freebsd-update?
> 
I suppose nothing, but most likely my lack of knowledge

> There's even a mostly automated process called `jailmanage update $jailname`

I was not aware of this option, hence it is also not mentioned somewhere. Or I did not look good enough..

https://github.com/msimerson/Mail-Toaster-6/wiki/Updating for example doesn't mention it..

**Comment by msimerson** [comment]
I never thought to add docs about it in MT6. [Jailmanage](https://github.com/msimerson/jailmanage) predates MT6 by quite a lot and MT6 installs it on the host already.

**Comment by Infern1** [comment]
Makes perfect sense, then I would just make reference to the update method possible by jailmanage

I'm following this project for a while but did not know, so possible other users also don't. I would use this method now surely for customized jails.

**Comment by msimerson** [comment]
I added a link
