### ISSUE TITLE
NS records not listed for $TOASTER_MAIL_DOMAIN

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#458]
**Describe the bug**
requesting name servers for the configured TOASTER_MAIL_DOMAIN doesn't work due to setup of unbound

**Expected behavior**
return ns records for TOASTER_MAIL_DOMAIN by unbound

I found in this [article ](https://utcc.utoronto.ca/~cks/space/blog/sysadmin/UnboundLocalDNSOverride)

That by defining `local-data`  for unbound it overrides all settings, configured in the real auth DNS server

> We've supplied our own A record for server.example.com, but we've also effectively deleted all other DNS records for it. If it has an MX record or a TXT record or what have you, those records will not be visible. For any names in transparent local-data zones, you are in complete control of all records returned; either they're in your local-data stanzas, or they don't exist.

>**Note that if you just give local-data for something without a local-zone directive, Unbound silently makes it into such a transparent local zone.**

So if configure `TOASTER_MAIL_DOMAIN` as `foo.com` and I have all my jails: `smtp,vpopmail, etc...` I am not able to request the originating DNS servers by.

Example:
```
 >dig @8.8.8.8 bsdfreaks.nl ns

; <<>> DiG 9.16.8 <<>> @8.8.8.8 bsdfreaks.nl ns
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53139
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;bsdfreaks.nl.			IN	NS

;; ANSWER SECTION:
bsdfreaks.nl.		21599	IN	NS	ns0.transip.net.
bsdfreaks.nl.		21599	IN	NS	ns2.transip.eu.
bsdfreaks.nl.		21599	IN	NS	ns1.transip.nl.

;; Query time: 16 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Nov 22 22:50:32 CET 2020
;; MSG SIZE  rcvd: 124
```

So the real NS server is ns0.transip.net

If I make the same request to unbound:
```
>dig bsdfreaks.nl ns

; <<>> DiG 9.16.8 <<>> bsdfreaks.nl ns
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 60430
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;bsdfreaks.nl.			IN	NS

;; Query time: 0 msec
;; SERVER: 172.16.15.3#53(172.16.15.3)
;; WHEN: Sun Nov 22 22:52:12 CET 2020
;; MSG SIZE  rcvd: 41
```

It doesn't find any NS records, which is not correct and gives my some problems with certbot DNS method
If I add:
```
local-zone: bsdfreaks.nl typetransparent
```
to `/data/mt6-local.conf`   unbound responds correctly:

```
>dig bsdfreaks.nl ns

; <<>> DiG 9.16.8 <<>> bsdfreaks.nl ns
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 54785
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;bsdfreaks.nl.			IN	NS

;; ANSWER SECTION:
**bsdfreaks.nl.		86400	IN	NS	ns2.transip.eu.
bsdfreaks.nl.		86400	IN	NS	ns0.transip.net.
bsdfreaks.nl.		86400	IN	NS	ns1.transip.nl.**

;; Query time: 3 msec
;; SERVER: 172.16.15.3#53(172.16.15.3)
;; WHEN: Sun Nov 22 22:54:22 CET 2020
;; MSG SIZE  rcvd: 124
```

All other records defined as `local-data` are still found.

**Comment by msimerson** [comment]
This is a tricky area for MT to address. One can deploy MT6 with a wide variety of network setups, including on public IPs, private IPs, loopback IPs, etc. DNS for each type of setup will necessarily require a few customizations,  which is why unbound.conf.local exists. I deploy my setups on loopback IPs (the default) and then configure unbound with split horizon DNS. That way, all the VM hostnames, SPF, and NS records resolve to values that are reachable behind the NAT / public IP. In practice, that means that my mail server canonical hostname has a A and AAAA entries with loopback IPs as well as MX and SPF records that are valid on the loop net. YMMV.
