### ISSUE TITLE
Possibility to deploy in alternative datasets than /jail and /data mountpoints

### ISSUE THREAD

**Issue by zenny** [msimerson/Mail-Toaster-6#469]
**Is your feature request related to a problem? Please describe.**
Trying to deploy multiple clients owning multiple domains by provisioning the relevant services in `/jails/clientN/$name/$domain` and `/data/clientN/$name/$domain` in the same server instead of directly deploying to the root of `/jails` and `/data` mountpoints.

This could be useful as the servers are having more resources today.

**Describe the solution you'd like**
It would be nice to bootstrap the script  for multiple clients with multiple domains can be hosted in the single server by separating the private network IPs with specific ACL (chown) permission to the specific `$client` to the services running in jails.

**Describe alternatives you've considered**
Maybe specifying:

```
ZFS_JAIL_VOL="${ZFS_VOL}${ZFS_JAIL_MNT}${CLIENT}${DOMAIN}${NAME}"
ZFS_DATA_VOL="${ZFS_VOL}${ZFS_DATA_MNT}${CLIENT}${DOMAIN}${NAME}"

```

**Additional context**
`CLIENT` can be serialized which owns `DOMAINs` (`domain.tld, www.domain.tld, sub.domain.tld, mail.domain.tld, webmail.domain.tld , nsX.domain.tld` among others) whereas `NAME` denotes the service name under `/provision` directory. `JAIL/DATA-PATH` for specific domains assigned with specific ACL to the specific `CLIENT` would be wonderful in addition to assigning separate `cloned_interfaces` to every client serialized.

In this scenario, a single instance of `dns` and two load-balanding/redundant `haproxy` jails may be enough to point to relevant services based on `domain.tld`. For specific `client` access, an additional `OpenVPN` jail would be a good addition, imo. 

Topology
Internet >> DNS >> Haproxy-pair >> Domain specific services

Cheers and stay safe,

**Comment by msimerson** [comment]
This is rather an "adjacent mt6" type of feature.

MT6 is designed around shared services. When you consider MySQL, Apache, MongoDB, dovecot, clamav, rspamd, and others, they are resource intensive services for which it makes little sense to have many micro-instances of. The exceptions are the very lightweight instances like nginx and tinydns.

As you point out, jails are also useful for isolating clients. I do this myself, creating snowflake (one offs) jails for clients that have particular needs: dedicated IP, DNS server, private mail store, a PBX, etc. For those instances, I deploy them in a separate private network (from mt6 jails) but the disk layout still follows the mt6 pattern and all the snowflake jails have access to the mt6 shared services. Ex:

````
/data/clientX/
/jails/clientX/
````

What is done inside those jails I consider out-of-scope for mt6. IOW, do whatever you want. In my case, each one is a snowflake and I encode the uniqueness in a provisioning script.

If you're convinced this idea is worth the effort, work up a PR that implements it and we'll discuss further.
