### ISSUE TITLE
vpopmail build broken FreeBSD 13

### ISSUE THREAD

**Issue by Infern1** [msimerson/Mail-Toaster-6#487]
**Describe the bug**
vpopmail fails to build

see here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=257672

**Comment by Infern1** [comment]
Add the flags to vpopmail Makefile indeed fixes the problem

**Comment by msimerson** [comment]
A convenient and durable workaround for this is adding `CFLAGS+=    -fcommon` to /jails/vpopmail/etc/make.conf.

**Comment by msimerson** [comment]
fixed by #512
