### ISSUE TITLE
haraka refuses to start, tests fail when setting up jail

### ISSUE THREAD

**Issue by johannes73** [msimerson/Mail-Toaster-6#49]
I would like to migrate an MT5 server to a new MT6 server. Even though I have used MT5 for many years, I am new to MT6, so please bear with me. 

I begin with a fresh FreeBSD 10.3-RELEASE server, and follow the instructions on these pages:
https://github.com/msimerson/Mail-Toaster-6/wiki/FreeBSD
https://github.com/msimerson/Mail-Toaster-6/wiki/Jails

### Expected behavior

After having completed all steps up to "provision dovecot" (except for dspam that is stricken), I try to provision the haraka jail:
 
provision haraka

(...)
   ***   waiting for Haraka to start listeners   ***
   ***   testing Haraka   ***

root     node       98329 89 tcp4   172.16.15.254:25      *:*
it worked    <===== THIS IS WHAT I WOULD LIKE TO SEE
(...)
Success! A new 'haraka' jail is provisioned    <===== THIS IS WHAT I WOULD LIKE TO SEE

### Observed behavior

But this is what happens:

(...)
   ***   starting haraka   ***

sysrc -R /jails/stage haraka_enable=YES
haraka_enable:  -> YES
haraka_flags:  -> -c /usr/local/haraka
jexec stage service haraka start
loaded TLD files: 1=1408 2=5987 3=2318
loaded 8020 Public Suffixes
loglevel: LOGINFO
Starting up Haraka version 2.8.8
[INFO] [-] [core] Loading plugins
[INFO] [-] [core] Loading plugin: process_title
[INFO] [-] [core] Loading plugin: log.syslog
[INFO] [-] [core] Loading plugin: access
[INFO] [-] [access] skipping helo.checks.regexps
[INFO] [-] [core] Loading plugin: connect.p0f
[INFO] [-] [core] Loading plugin: connect.geoip
[INFO] [-] [connect.geoip] provider maxmind with 6 DBs
[INFO] [-] [core] Loading plugin: connect.fcrdns
[INFO] [-] [core] Loading plugin: dnsbl
[INFO] [-] [core] Loading plugin: helo.checks
[INFO] [-] [core] Loading plugin: tls
[INFO] [-] [core] Loading plugin: auth/auth_vpopmaild
[INFO] [-] [core] Loading plugin: mail_from.is_resolvable
[INFO] [-] [core] Loading plugin: spf
[INFO] [-] [core] Loading plugin: rcpt_to.qmail_deliverable
[INFO] [-] [core] Loading plugin: bounce
[INFO] [-] [core] Loading plugin: data.headers
[INFO] [-] [core] Loading plugin: data.uribl
[INFO] [-] [core] Loading plugin: attachment
[INFO] [-] [core] Loading plugin: clamd
[INFO] [-] [clamd] Loading excludes file
[INFO] [-] [core] Loading plugin: avg
[INFO] [-] [core] Loading plugin: spamassassin
[INFO] [-] [core] Loading plugin: rspamd
[INFO] [-] [core] Loading plugin: dkim_sign
[INFO] [-] [core] Loading plugin: karma
[INFO] [-] [core] Loading plugin: queue/smtp_forward
[INFO] [-] [core] Loading plugin: limit
[INFO] [-] [core] Loading plugin: watch
[INFO] [-] [core] Loading plugin: redis

   ***   waiting for Haraka to start listeners   ***

   ***   testing Haraka   ***

(HERE THE TEST EXITS, AND THE SCRIPT DOES NOT COMPLETE WITH "Success" AS THE OTHER SCRIPTS.)

# 
### Steps to reproduce

Follow the instructions on the web page, on a new FreeBSD 10.3-RELEASE server. 

Any ideas what I should do? Very thankful for a kick in the right direction...

**Comment by msimerson** [comment]
When I last looked at this, the issue was the node-syslog plugin was not compatible with node version 6. I was able to get it working by instead installing node v4. 

See haraka/Haraka#1546 and strongloop/modern-syslog#16.

**Comment by msimerson** [comment]
Hrmm, looks like the patch that fixes the syslog problem is in the repo but they haven't released a new version of modern-syslog yet. For now, that can be worked around by telling npm to install modern-syslog from the github repo by changing the version number (in Haraka's package.json) to "strongloop/modern-syslog"

**Comment by msimerson** [comment]
So far, the easiest way to work around this issue is to drop into the Haraka stage jail (`jexec stage bash`) and reinstall modern-syslog and Haraka with these commands:

```sh
rm -rf /usr/local/lib/node_modules/Haraka
pkg install -y git
npm install -g strongloop/modern-syslog Haraka
promote_staged_jail haraka
```

That installs the latest version of modern-syslog from the upstream git repo, Haraka inherits that version, and all works.

**Comment by johannes73** [comment]
Matt, you really are the man. A big thank you for your prompt help; I really appreciate it. 

Actually, I could run all the commands you suggested, but the last one failed for me: 
promote_staged_jail haraka

But it seems to work, and the jail is provisioned, when I edit and run the provision-haraka.sh script manually:

I commented out this line:
#stage_exec npm install -g Haraka ws express || exit

And inserted these lines, based on your suggestion, below it:
stage_exec pkg install -y git
stage_exec npm install -g strongloop/modern-syslog Haraka ws express || exit

It seems to work now. Thanks again.
