### ISSUE TITLE
Dovecot not promoting

### ISSUE THREAD

**Issue by lunaticds** [msimerson/Mail-Toaster-6#496]
### Expected behavior
Dovecot jail to promote successfully
### Observed behavior
   ***   starting dovecot   ***

sysrc -R /jails/stage dovecot_enable=YES
dovecot_enable:  -> YES
sysrc -R /jails/stage dovecot_config=/data/etc/dovecot.conf
dovecot_config:  -> /data/etc/dovecot.conf
jexec stage service dovecot start
Starting dovecot.

   ***   testing dovecot   ***

checking for port 993 listener in staged jail
	checking port 993

Success! Port 993 is listening in staging jail
checking for port 995 listener in staged jail
	checking port 995

Success! Port 995 is listening in staging jail
Updating FreeBSD repository catalogue...
FreeBSD repository is up to date.
All repositories are up to date.
The following 1 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
	empty: 0.6.20b

Number of packages to be installed: 1

18 KiB to be downloaded.
[1/1] Fetching empty-0.6.20b.pkg: 100%   18 KiB  18.6kB/s    00:01    
Checking integrity... done (0 conflicting)
[1/1] Installing empty-0.6.20b...
[1/1] Extracting empty-0.6.20b: 100%
testing IMAP AUTH as postmaster@xxxxxxx.net.au
Can't use SSL_get_servername
depth=0 C = AU, ST = Victoria, L = Ballarat, O = xxxxxxxx, CN = mail2.xxxxxxx.net.au, emailAddress = postmaster@xxxxxxxx.net.au
verify error:num=18:self signed certificate
verify return:1
depth=0 C = AU, ST = Victoria, L = Ballarat, O = xxxxxxxxxxx, CN = mail2.xxxxxxx.net.au, emailAddress = postmaster@xxxxxxxx.net.au
verify return:1
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5] Mail Toaster (Dovecot) ready.
empty: Data stream is empty. Keyphrase wasn't found. Exit on timeout
empty: Data stream is empty. Keyphrase wasn't found. Exit on timeout
* OK Waiting for authentication process to respond..
empty: Data stream is empty. Keyphrase wasn't found. Exit on timeout
Logout completed

### Steps to reproduce
Followed install guide on fresh 12.2-REL-p7 build. No CA signed cert. Repeated behaviour on 5 fresh builds. 
Above occurs.Jail does not provision at all.

**Comment by msimerson** [comment]
You need to figure out why authentication is failing in the newly provisioned jail. Is this an upgrade?  If so, did you make the auth backend changes required? (see [UPDATING](https://github.com/msimerson/Mail-Toaster-6/wiki/Updating))

**Comment by lunaticds** [comment]
Completely fresh build - all 5 builds have resulted in the same occurrence.

**Comment by msimerson** [comment]
You can promote the jail anyway with: `promote_staged_jail dovecot` and it'll probably be fine. I'll see if I can't replicate the issue.
