### ISSUE TITLE
npm ERR! An unknown git error occurred

### ISSUE THREAD

**Issue by rricker1** [msimerson/Mail-Toaster-6#532]
**Describe the bug**
 Receiving the following error when upgrading haraka:

   ***   installing Haraka   ***

jexec stage bash -c npm install -g --omit=dev https://github.com/haraka/Haraka.git
npm ERR! code 128
npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/haraka/Haraka.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-02-04T02_50_44_183Z-debug-0.log

**debug log:**

0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@9.1.2
2 info using node@v16.19.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 4ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 2ms
13 timing config:load:global Completed in 3ms
14 timing config:load:setEnvs Completed in 2ms
0 verbose cli /usr/local/bin/node /usr/local/bin/npm
1 info using npm@9.1.2
2 info using node@v16.19.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 4ms
8 timing config:load:env Completed in 1ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/root/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 2ms
13 timing config:load:global Completed in 3ms
14 timing config:load:setEnvs Completed in 2ms
15 timing config:load Completed in 16ms
16 timing npm:load:configload Completed in 17ms
17 timing npm:load:mkdirpcache Completed in 0ms
18 timing npm:load:mkdirplogs Completed in 0ms
19 verbose title npm install https://github.com/haraka/Haraka.git
20 verbose argv "install" "--global" "--omit" "dev" "https://github.com/haraka/Haraka.git"
21 timing npm:load:setTitle Completed in 3ms
22 timing config:load:flatten Completed in 6ms
23 timing npm:load:display Completed in 7ms
24 verbose logfile logs-max:10 dir:/root/.npm/_logs/2023-02-04T02_50_44_183Z-
25 verbose logfile /root/.npm/_logs/2023-02-04T02_50_44_183Z-debug-0.log
26 timing npm:load:logFile Completed in 10ms
27 timing npm:load:timers Completed in 0ms
28 timing npm:load:configScope Completed in 0ms
29 timing npm:load Completed in 39ms
30 timing config:load:flatten Completed in 1ms
31 timing arborist:ctor Completed in 1ms
32 silly logfile done cleaning log files
33 timing idealTree:init Completed in 11ms
34 timing idealTree Completed in 3393ms
35 timing command:install Completed in 3408ms
36 verbose stack Error: An unknown git error occurred
36 verbose stack     at makeError (/usr/local/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:28:13)
36 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:37:26
36 verbose stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
37 verbose cwd /
38 verbose FreeBSD 12.4-RELEASE
39 verbose node v16.19.0
40 verbose npm  v9.1.2
41 error code 128
42 error An unknown git error occurred
43 error command git --no-replace-objects ls-remote ssh://git@github.com/haraka/Haraka.git
44 error git@github.com: Permission denied (publickey).
44 error fatal: Could not read from remote repository.
44 error
44 error Please make sure you have the correct access rights
44 error and the repository exists.
45 verbose exit 128
46 timing npm Completed in 3480ms
47 verbose unfinished npm timer reify 1675479044254
48 verbose unfinished npm timer reify:loadTrees 1675479044259
49 verbose unfinished npm timer idealTree:userRequests 1675479044272
50 verbose code 128
51 error A complete log of this run can be found in:
51 error     /root/.npm/_logs/2023-02-04T02_50_44_183Z-debug-0.log

**To Reproduce**
provision haraka

**Server (please complete the following information):**
 - OS: FreeBSD
 - Version 12.4-RELEASE

**Comment by msimerson** [comment]
This is caused by a 🤦🏻‍♂️ bug in NPM v7, see npm/cli#2610. I'll have a workaround soon.
