### ISSUE TITLE
provision clamav broken due changed startscript names 

### ISSUE THREAD

**Issue by tniethammer** [msimerson/Mail-Toaster-6#585]
**Describe the bug**
during build the builder stop with error:

in provision/clamav.sh on line 234
sed: /jails/stage/usr/local/etc/rc.d/clamav-clamd: No such file or directory 

in provision/clamav.sh on line 260
sed: /jails/stage/usr/local/etc/rc.d/clamav-freshclam: No such file or directory

in provision/clamav.sh on line 279
stage_exec service clamav-clamd start --> stage_exec service clamav_clamd start

in provision/clamav.sh on line 283
stage_exec service clamav-freshclam start --> stage_exec service clamav_clamd start

Config file changed from "clamav-clamd" to "clamav_clamd" and "clamav-freshclam" to "freshclam_freshclam"

**To Reproduce**
provision clamav

**Expected behavior**
modifie the config file and finish building of jail

**Screenshots**

**Server (please complete the following information):**
Freebsd 13.3 p6
clamav-1.4.1_2,1

**Comment by msimerson** [comment]
Fixed in d365bad
