### ISSUE TITLE
Consider to add support for IP2Location.io API

### ISSUE THREAD

**Issue by ip2location** [msimerson/Mail-Toaster-6#586]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Add IP2Location.io API as a fallback.

**Describe alternatives you've considered**
No.

**Additional context**
Our service provided 500 queries per day for keyless query, or 30000 queries per month if you sign up our free plan. You can read more on the result returned via [our documentation](https://www.ip2location.io/ip2location-documentation).

**Comment by msimerson** [comment]
I'd consider a PR that implements this but I don't anticipate spending any of my own effort. A mere 500 or 1,000 qpd wouldn't suffice for even a personal mail server with a few domains.
