### ISSUE TITLE
A couple of issues with host.sh

### ISSUE THREAD

**Issue by rricker1** [msimerson/Mail-Toaster-6#589]
**Describe the bug**
When following the setup instructions for FreebSD then moving forward through the MT6 install instructions host.sh fails as /usr/local/bin and /usr/local/etc/rc.d are not created on the fresh system. Also host.sh installs a firewall with IPv4 and IPv6 support however, if you do not have an IPv6 address the firewall fails to start.

**Error Messages**
<snip>
   ***   installing jailmanage   ***

fetch: /usr/local/bin/jailmanage: open(): No such file or directory
</snip>

<snip>
   ***   starting sshd earlier   ***

tee: /usr/local/etc/rc.d/sshd_reorder: No such file or directory
</snip>

<snip>
Enabled
/etc/pf.conf:7: syntax error
pfctl: Syntax error in config file: pf rules not loaded
</snip>

**To Reproduce**
Fresh install of FreeBSD then start the MT6 install

**Expected behavior**
provision host succeeds and new jail is promoted

**Server (please complete the following information):**
FreeBSD-13.3-RELEASE

**Additional context**
I have attached a patch that should correct the issues
[host.patch](https://github.com/user-attachments/files/17387968/host.patch)

**Comment by rricker1** [comment]
Fixed typo in patch file
[host.patch](https://github.com/user-attachments/files/17388531/host.patch)

**Comment by msimerson** [comment]
Thanks @rricker1 

Can you test that this patch also does the needful in your environment:

```diff
diff --git a/provision/host.sh b/provision/host.sh
index 6d94a95..894499d 100755
--- a/provision/host.sh
+++ b/provision/host.sh
@@ -205,6 +205,7 @@ sshd_reorder()
        fi
 
        tell_status "starting sshd earlier"
+       if [ ! -d "/usr/local/etc/rc.d" ]; then mkdir -p "/usr/local/etc/rc.d"; fi
        tee "$_file" <<EO_SSHD_REORDER
 #!/bin/sh
 # start up sshd earlier, particularly before jails
@@ -402,6 +403,12 @@ pass  in quick on \$ext_if proto tcp to port ssh \
 anchor "allow/*"
 EO_PF_RULES
 
+       if [ -z "$PUBLIC_IP6" ]; then
+               sed -i '' \
+                       -e '/^table <ext_ip>/ s/, \$ext_ip6//' \
+                       /etc/pf.conf
+       fi
+
        kldstat -q -m pf || kldload pf
 
        grep -q ^pf_enable /etc/rc.conf || sysrc pf_enable=YES
@@ -419,6 +426,7 @@ install_jailmanage()
        if [ -s /usr/local/bin/jailmanage ]; then return; fi
 
        tell_status "installing jailmanage"
+       if [ ! -d "/usr/local/bin" ]; then mkdir -p "/usr/local/bin"; fi
        fetch -o /usr/local/bin/jailmanage https://raw.githubusercontent.com/msimerson/jailmanage/master/jailmanage.sh
        chmod 755 /usr/local/bin/jailmanage
 }
```

**Comment by rricker1** [comment]
Tested. Patch failed to apply:

<p>
# patch < host.patch <br />
Hmm...  Looks like a unified diff to me...<br />
The text leading up to this was:<br />
--------------------------<br />
|diff --git a/provision/host.sh b/provision/host.sh<br />
|index 6d94a95..894499d 100755<br />
|--- a/provision/host.sh<br />
|+++ b/provision/host.sh<br />
--------------------------<br />
Patching file provision/host.sh using Plan A...<br />
Hunk #1 failed at 205.<br />
Hunk #2 failed at 403.<br />
Hunk #3 failed at 426.<br />
3 out of 3 hunks failed--saving rejects to provision/host.sh.rej<br />
done<br />
</p>

I applied the modifications by hand. host.sh finished without errors and all issues were corrected.

**Comment by msimerson** [comment]
thanks @rricker1
