### ISSUE TITLE
geoip.sh fails using maxmind-geolite-mirror while downloading DB's

### ISSUE THREAD

**Issue by rricker1** [msimerson/Mail-Toaster-6#591]
**Describe the bug**
When attempting to download DB's maxmind-geolite-mirror stalls while maxing out connection attempts before finally failing. I receive an email notification "Daily GeoIP Database Download Limit Reached".

**To Reproduce**
provision geoip

**Expected behavior**
databases should be downloaded, jail should be promoted.

**Server (please complete the following information):**
FreeBSD-13.3

**Additional context**
Adding:
export GEOIP_UPDATER="geoipupdate"
export MAXMIND_ACCOUNT_ID="XXXXXXX"

to mail mail-toaster.conf completes as expected.

Q. Is maxmind-geolite-mirror preferfred over geoipupdate?

**Comment by msimerson** [comment]
A: maxmind-geolite-mirror is currently broken. See msimerson/maxmind-geolite-mirror#47

**Comment by rricker1** [comment]
I'm not sure that my question was answered. Is one better/preferred than the other?

Should export GEOIP_UPDATER="" and export MAXMIND_ACCOUNT_ID="" be included in mail-toaster.conf.

**Comment by msimerson** [comment]
Yes, the one that works is preferred. 

They're both very simple utilities that fetch files into a local directory. If MaxMind hasn't made a mess with their old perl based updater, I'd have never bothered to write maxmind-geolite-mirror. Now that they've got a well functioning updater,  and they're probably going to keep futzing with how they're hosting the files, it's probably best to deprecate maxmind-geolite-updater and prefer geoipupdate.

**Comment by rricker1** [comment]
Thank you for the explanation.
