### ISSUE TITLE
dovecot.sh still fails error:  provision/dovecot.sh: curl: not found

### ISSUE THREAD

**Issue by rricker1** [msimerson/Mail-Toaster-6#594]
**Describe the bug**'

dovecot.sh still fails error:  provision/dovecot.sh: curl: not found

**To Reproduce**
provision dovecot

**Expected behavior**
provision dovecot.sh should complete and dovecot jail should be promoted

**Error:**

testing IMAP AUTH as postmaster@XXXXXXXX.com
jexec stage curl -k -v --login-options AUTH=PLAIN imaps://postmaster%40pcaliance.com:Unn2YZXgiElNph@localhost/
* Host localhost:993 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:993...
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / [blank] / UNDEF
* Server certificate:
*  subject: C=US; ST=Washington; L=Southworth; O=PC Aliance; CN=pcaliance.com; emailAddress=postmaster@pcaliance.com
*  start date: Oct 16 20:55:09 2024 GMT
*  expire date: Oct 15 20:55:09 2030 GMT
*  issuer: C=US; ST=Washington; L=Southworth; O=PC Aliance; CN=pcaliance.com; emailAddress=postmaster@pcaliance.com
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
*   Certificate level 0: Public key type ? (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
* Connected to localhost (::1) port 993
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< * OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5 AUTH=SCRAM-SHA-1 AUTH=SCRAM-SHA-256] Mail Toaster (Dovecot) ready.
> A001 CAPABILITY
< * CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN AUTH=DIGEST-MD5 AUTH=CRAM-MD5 AUTH=SCRAM-SHA-1 AUTH=SCRAM-SHA-256
< A001 OK Pre-login capabilities listed, post-login capabilities have more.
> A002 AUTHENTICATE PLAIN AHBvc3RtYXN0ZXJAcGNhbGlhbmNlLmNvbQBVbm4yWVpYZ2lFbE5waA==
< * CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY PREVIEW STATUS=SIZE SAVEDATE LITERAL+ NOTIFY SPECIAL-USE QUOTA
< A002 OK Logged in
> A003 LIST "" *
< * LIST (\HasNoChildren) "." INBOX
* LIST (\HasNoChildren) "." INBOX
< A003 OK List completed (0.004 + 0.000 + 0.003 secs).
* Connection #0 to host localhost left intact
provision/dovecot.sh: curl: not found

**Server (please complete the following information):**
FreeBSD-13.3-RELEASE

**Comment by msimerson** [comment]
Oh right, two tests. A better encapsulated fix:

```diff
diff --git a/include/mua.sh b/include/mua.sh
index a42c071..65323de 100755
--- a/include/mua.sh
+++ b/include/mua.sh
@@ -40,20 +40,24 @@ test_imap_openssl()
 EOF
 }
 
+get_curl_cmd()
+{
+       if [ -x /usr/local/bin/curl ]; then
+               echo "curl"
+       elif [ -x "$STAGE_MNT/usr/local/bin/curl" ]; then
+               echo "stage_exec curl"
+       else
+               pkg install -qy curl
+               echo "curl"
+       fi
+}
+
 test_imap_curl()
 {
        local _test_uri
        _test_uri="imaps://$(uriencode $MUA_TEST_USER):$(uriencode $MUA_TEST_PASS)@${MUA_TEST_HOST}/"
-
-       if [ -x /usr/local/bin/curl ]; then
-               curl -k -v --login-options 'AUTH=PLAIN' "$_test_uri"
-       elif [ -x "$STAGE_MNT/usr/local/bin/curl" ]; then
-               _test_uri="imaps://$(uriencode $MUA_TEST_USER):$(uriencode $MUA_TEST_PASS)@localhost/"
-               stage_exec curl -k -v --login-options 'AUTH=PLAIN' "$_test_uri"
-       else
-               pkg install -y curl
-               curl -k -v --login-options 'AUTH=PLAIN' "$_test_uri"
-       fi
+       _curl_cmd="$(get_curl_cmd)"
+       $_curl_cmd -k -v --login-options 'AUTH=PLAIN' "$_test_uri"
 }
 
 test_imap()
@@ -90,9 +94,11 @@ test_pop3_empty()
 
 test_pop3()
 {
+       local _test_uri
+       _test_uri="pop3s://$(uriencode $MUA_TEST_USER):$(uriencode $MUA_TEST_PASS)@${MUA_TEST_HOST}/"
+       _curl_cmd="$(get_curl_cmd)"
        # shellcheck disable=2001
-       curl -k -v --login-options 'AUTH=PLAIN' \
-               "pop3s://$(uriencode $MUA_TEST_USER):$(uriencode $MUA_TEST_PASS)@${MUA_TEST_HOST}/"
+       $_curl_cmd -k -v --login-options 'AUTH=PLAIN' "$_test_uri"
 }
 
 uriencode() {
```

**Comment by rricker1** [comment]
Tried to apply the patch thusly patch < mua.patch which failed. I'm not sure if i am apply incorrectly. I haven't worked with patch files since the early MT5 days. If I'm missing something here, please let me know.

I applied the patch manually. dovecot.sf failed with curl not found error. Tested a secon time to make sure.

< A001 OK Pre-login capabilities listed, post-login capabilities have more.
> A002 AUTHENTICATE PLAIN AHBvc3RtYXN0ZXJAcGNhbGlhbmNlLmNvbQBVbm4yWVpYZ2lFbE5waA==
< * CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE SORT SORT=DISPLAY THREAD=REFERENCES THREAD=REFS THREAD=ORDEREDSUBJECT MULTIAPPEND URL-PARTIAL CATENATE UNSELECT CHILDREN NAMESPACE UIDPLUS LIST-EXTENDED I18NLEVEL=1 CONDSTORE QRESYNC ESEARCH ESORT SEARCHRES WITHIN CONTEXT=SEARCH LIST-STATUS BINARY MOVE SNIPPET=FUZZY PREVIEW=FUZZY PREVIEW STATUS=SIZE SAVEDATE LITERAL+ NOTIFY SPECIAL-USE QUOTA
< A002 OK Logged in
> A003 LIST "" *
< * LIST (\HasNoChildren) "." INBOX
* LIST (\HasNoChildren) "." INBOX
< A003 OK List completed (0.001 + 0.000 secs).
* Connection #0 to host localhost left intact
provision/dovecot.sh: curl: not found
