### ISSUE TITLE
provision haraka fails

### ISSUE THREAD

**Issue by rricker1** [msimerson/Mail-Toaster-6#596]
**Describe the bug**
haraka.sh fails. ERROR: stage_enable_newsyslog: not found

**To Reproduce**
Steps to reproduce the behavior:provision haraka

**Expected behavior**
haraka.sh completes-new jail is promoted

**ERROR:**
   ***   rejecting brutefore AUTH signature   ***

ylmf\-pc
provision/haraka.sh: stage_enable_newsyslog: not found

**Server**
FreeBSD-13.3-RELEASE

**Comment by msimerson** [comment]
try:

```
. mail-toaster.sh
mt6-update
provision haraka
```

**Comment by rricker1** [comment]
That worked. Thank you.
