### ISSUE TITLE
provision letsencrypt fails

### ISSUE THREAD

**Issue by rricker1** [msimerson/Mail-Toaster-6#598]
**Describe the bug**
provision letsencrypt fails

**To Reproduce**
provision letsencrypt

**Expected behavior**

**ERROR**
provision/letsencrypt.sh: /root/.acme.sh/acme.sh: not found

**Server (please complete the following information):**
FreeBSD-13.3-RELEASE

**Additional context**
letsencrypt.sh is looking for acme.sh in "/root/.acme.sh/" when it is located in "/usr/local/sbin/acme.sh". I linked "/usr/local/sbin/acme.sh" to "/root/.acme.sh/" for testing which corrected the problem.  

# ln -s /usr/local/sbin/acme.sh /root/.acme.sh/

**Comment by msimerson** [comment]
Should be fixed by d6d5288
