### ISSUE TITLE
Running provision base fails because lo1 doesnt exist

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#67]
provision base
.
.
.
   ***   stage jail base startup   ***

ifconfig: interface lo1 does not exist
jail: /sbin/ifconfig lo1 inet 172.16.15.254 netmask 255.255.255.255 alias: failed

Workaround:
# ifconfig l01 create

Continuing:
  ***   stage jail base startup   ***

Setting hostname: base.
Starting syslogd.
syslogd: timed out waiting for child
/etc/rc: WARNING: failed to start syslogd
ELF ldconfig path: /lib /usr/lib /usr/lib/compat
32-bit compatibility ldconfig path: /usr/lib32
Clearing /tmp (X related).
Starting cron.

Sun Sep 25 03:40:26 EDT 2016
Updating FreeBSD repository catalogue...
pkg: http://pkg.FreeBSD.org/FreeBSD:10:amd64/quarterly/meta.txz: No address record
repository FreeBSD has no meta file, using default settings
pkg: http://pkg.FreeBSD.org/FreeBSD:10:amd64/quarterly/packagesite.txz: No address record
Unable to update repository FreeBSD

Presumably above error is freebsd.org not Mail-Toaster-6

**Comment by msimerson** [comment]
> Presumably above error is freebsd.org not Mail-Toaster-6

Looks to me like PEBKAC. If you're following the instructions, you can't get to `provision base` without lo1 being provisioned.

**Comment by toastedmail** [comment]
When a new VPS was created and running the initial script 'sh 
mail-toaster.sh' it fails at end saying there is no lo1. Created lo1 
manually and then continued.

Thing is, why did you not add simple text on your site saying haraka no 
longer is in /usr/local/haraka and write haraka/config is now in 
/data/haraka ?? It would have saved a ton of time knowing this in advance.

What is PEBKAC?

Regards,
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
Lanny Baron
BaronTEL

The Future of Business Telephony Services is Here and Now!

Tel: 416.477.5411
Toll-Free: 888.241.8647
Fax: 647.693.9492
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
