### ISSUE TITLE
New Install of Mail-Toaster no vpopmail users

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#86]
Installed Mail-Toaster 6 in a FreeBSD 10.3 vm.

Since our current Mail-Toaster is not working, logged into old Mail-Toaster server ran:
#jailmanage mysql 

mysqldump vpopmail > /root/vpopmaill.sql

Rsync'd the vpopmail.sql to new Mail-Toaster Server and ran:
#jailmanage mysql
#mysql vpopmail < vpopmail.sql

However running #~vpopmail/bin/vuserinfo user@domain.tld displays no such user

Vpopmail db definitely has the users and domains when running jailmanage mysql, #mysql vpopmail, 
mysql>  select * from vpopmail;

All domains/users and clear passwords are displayed.

Why then when running ~vpopmail/bin/vuserinfo user@some-domain.tld show as no such user??

Please help.
Thank you.

**Comment by msimerson** [comment]
Vpopmail depends on qmail, and consequently, the qmail control files which appear to be missing.

**Comment by toastedmail** [comment]
What to do to get qmail installed properly then?
