### ISSUE TITLE
provision haraka also doesnt start

### ISSUE THREAD

**Issue by toastedmail** [msimerson/Mail-Toaster-6#88]
#provision haraka
.
.
.

Stopping jails:.
jail -r haraka
zroot/data/haraka filesystem exists
zroot/jails/haraka.last filesystem exists
zfs destroy zroot/jails/haraka.last
zroot/jails/haraka filesystem exists
zfs rename zroot/jails/haraka zroot/jails/haraka.last
zfs rename zroot/jails/haraka.ready zroot/jails/haraka

   ***   haraka already in /etc/jail.conf   ***

   ***   service jail start haraka   ***

**Starting jails: cannot start jail  "haraka": 
jail: haraka: mount: /jails/haraka/data/avg: No such file or directory**
.

Success! A new 'haraka' jail is provisioned

**Comment by msimerson** [comment]
PEBKAC error.

**Comment by msimerson** [comment]
See [PEBKAC](http://lmgtfy.com/?q=pebkac+error)

**Comment by toastedmail** [comment]
YOU ARE NOT NICE!
YOU LEFT A LONG TIME SUPPORTER IN A TERRIBLE POSITION NEEDLESSLY
YOUR SETUP IS NOT WORKING. I HAVE FIXED IT.

SHAME ON YOU!

Regards,
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
Lanny Baron
BaronTEL

The Future of Business Telephony Services is Here and Now!

Tel: 416.477.5411
Toll-Free: 888.241.8647
Fax: 647.693.9492
+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
